### ISSUE TITLE
Missing "type" in event causes panic: interface conversion: interface is nil, not string

### ISSUE THREAD

**Issue by erikswanson** [mheese/journalbeat#1]
There must to be a "type" in the map passed to PublishEvent, otherwise the following panic occurs:

	2016/02/24 00:42:18.326375 geolite.go:24: INFO GeoIP disabled: No paths were set under shipper.geoip.paths
	2016/02/24 00:42:18.326794 logstash.go:105: INFO Max Retries set to: 3
	2016/02/24 00:42:18.477273 outputs.go:135: INFO Activated logstash as output plugin.
	2016/02/24 00:42:18.478217 publish.go:291: INFO Publisher name: cah-pentest.novalocal
	2016/02/24 00:42:18.480674 async.go:78: INFO Flush Interval set to: 1s
	2016/02/24 00:42:18.480777 async.go:84: INFO Max Bulk Size set to: 2048
	2016/02/24 00:42:18.481287 beat.go:238: INFO Init Beat: journalbeat; Version: 0.1.0
	2016/02/24 00:42:18.481789 journalbeat.go:60: INFO Journalbeat Config
	2016/02/24 00:42:18.482753 journalbeat.go:180: INFO Journalbeat Setup
	2016/02/24 00:42:18.484876 journalbeat.go:145: INFO Seek to cursor successful
	2016/02/24 00:42:18.485190 beat.go:267: INFO journalbeat sucessfully setup. Start running.
	2016/02/24 00:42:18.485230 journalbeat.go:224: INFO Journalbeat Run
	2016/02/24 00:42:18.487627 journalbeat.go:247: INFO Start sending events to output
	panic: interface conversion: interface is nil, not string

	goroutine 22 [running]:
	panic(0x927c80, 0xc820012b40)
		/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/1.6/src/runtime/panic.go:464 +0x3e6
	github.com/elastic/beats/libbeat/outputs/logstash.(*logstash).BulkPublish(0xc82000e7a0, 0x0, 0x0, 0x0, 0xc82030a000, 0x5, 0x800, 0x0, 0x0)
		/jenkins/workspace/journalbeat/src/github.com/elastic/beats/libbeat/outputs/logstash/logstash.go:172 +0x14f
	github.com/elastic/beats/libbeat/publisher.(*outputWorker).sendBulk(0xc82009a200, 0xc820031d98, 0xc82030a000, 0x5, 0x800)
		/jenkins/workspace/journalbeat/src/github.com/elastic/beats/libbeat/publisher/output.go:90 +0x190
	github.com/elastic/beats/libbeat/publisher.(*outputWorker).onBulk(0xc82009a200, 0xc820031d98, 0xc82030a000, 0x5, 0x800)
		/jenkins/workspace/journalbeat/src/github.com/elastic/beats/libbeat/publisher/output.go:66 +0x3ac
	github.com/elastic/beats/libbeat/publisher.(*outputWorker).onMessage(0xc82009a200, 0xffffffffffff0000, 0x0, 0x0, 0x0, 0xc82030a000, 0x5, 0x800)
		/jenkins/workspace/journalbeat/src/github.com/elastic/beats/libbeat/publisher/output.go:49 +0x79
	github.com/elastic/beats/libbeat/publisher.(*messageWorker).run(0xc82009a200)
		/jenkins/workspace/journalbeat/src/github.com/elastic/beats/libbeat/publisher/worker.go:69 +0x425
	created by github.com/elastic/beats/libbeat/publisher.(*messageWorker).init
		/jenkins/workspace/journalbeat/src/github.com/elastic/beats/libbeat/publisher/worker.go:55 +0x11e

(I'd attach a patch or pull request, but it's not worth hours of meetings with legal for a 1-liner. Sorry.)

**Comment by mheese** [comment]
yup, that's indeed a problem ... I'll fix it tomorrow in the morning... thanks for reporting!

**Comment by mheese** [comment]
@erikswanson, the latest commit adds the fields:
- type
- input_type

Also, with reconfiguration of the config file (see new one in repo), there is now a beat.name field with "journalbeat".

I'm thinking that input_type should probably get the journal.transport value, and type maybe the value of the executing command (or something else). E.g., that would make it really easy to identify audit or kernel logs.

Besides from that, please confirm that the latest commit/version fixes your immediate issue.

**Comment by erikswanson** [comment]
So, the new version no longer panics out, but with the config the way I want it, I seem to be triggering a bug in Logstash. Fun.

	logstash-beats_1 | {:timestamp=>"2016-02-24T17:41:58.587000+0000", :message=>"Beats input: unhandled exception", :exception=>#<NoMethodError: undefined method `force_encoding' for 0:Fixnum>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.0-java/lib/logstash/util/charset.rb:14:in `convert'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-plain-2.0.2/lib/logstash/codecs/plain.rb:35:in `decode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/logstash/inputs/beats.rb:33:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-multiline-2.0.7/lib/logstash/codecs/identity_map_codec.rb:158:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/logstash/inputs/beats_support/connection_handler.rb:58:in `process'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/logstash/inputs/beats_support/connection_handler.rb:33:in `accept'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/lumberjack/beats/server.rb:429:in `data'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/lumberjack/beats/server.rb:408:in `read_socket'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/lumberjack/beats/server.rb:420:in `ack_if_needed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/lumberjack/beats/server.rb:404:in `read_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/lumberjack/beats/server.rb:261:in `json_data_payload'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/lumberjack/beats/server.rb:178:in `feed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/lumberjack/beats/server.rb:311:in `compressed_payload'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/lumberjack/beats/server.rb:178:in `feed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/lumberjack/beats/server.rb:389:in `read_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/lumberjack/beats/server.rb:369:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/logstash/inputs/beats_support/connection_handler.rb:33:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/logstash/inputs/beats.rb:177:in `handle_new_connection'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/logstash/inputs/beats_support/circuit_breaker.rb:42:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/logstash/inputs/beats.rb:177:in `handle_new_connection'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.2/lib/logstash/inputs/beats.rb:133:in `run'"], :level=>:error}

...

Yep. That logstash problem above is triggered by `convert_to_numbers: true`. I can live with it being false for now. Thanks for landing this fix. 

Also, just FYI, the following simpler build instructions work just fine (at least for my purposes in a Jenkins job with a fresh empty GOPATH, tested by accident on both go 1.5.3 and 1.6):

    go get github.com/mheese/journalbeat
    go install github.com/mheese/journalbeat
