### ISSUE TITLE
journalbeat is logging to one logstash instance only

### ISSUE THREAD

**Issue by caspar2305** [mheese/journalbeat#101]
Hello,

I configured journalbeat to log to two logstash instances, but it seams to take only the first one in the list. In a different test stage it's working fine with the same setup, but different logstash instances.

I didn't find any documentation for journalbeat. So I would like to know about the algorithm how journalbeat is picking the logstash to log to (also in case one is not available) and also how exactly is the "loadbalance" feature is working, also in case of failure of one logstash instance.

Thanks in advance!

**Comment by nicorevin** [comment]
Hello, all the docs are inlined with the config template https://github.com/mheese/journalbeat/blob/master/etc/journalbeat.yml

More verbose docs are available in the filebeat docs https://www.elastic.co/guide/en/beats/filebeat/current/load-balancing.html

**Comment by caspar2305** [comment]
I knew about the documentation in the config file. The link to filebeat docs helped me a lot.
Thank you very much!

**Comment by akarshjain40** [comment]
Can any one send configured file of journalbeat ,such that it sends too logstash or elasticsearch
