### ISSUE TITLE
Filter fields enhancement

### ISSUE THREAD

**Issue by hookenz** [mheese/journalbeat#102]
Journald and filebeat produce a lot of data.  Most of it I don't use.  I'd like the ability to filter fields before they are sent to the output.  This would be a similar feature to filebeat's exclude_lines option.

e.g. 

    `exclude_fields = [ "UID", "GID", "_SYSTEMD_SLICE", "_CURSOR" ]`

In addition, it may make sense to drop whole lines for certain priorities.  e.g.

`exclude_entries = [ "DEBUG" ]`

Which could exclude whole entries containing "PRIORITY" : "7"

In addition, it would be useful to add a TYPE field.  Similar to the now deprecated feature document_type which I think just sets the type field.  In filebeat this is done by log file path.  But in journalbeat everything in the journal is lumped together so we need a way to recognise what they are.  e.g. unit name filter?

**Comment by hookenz** [comment]
Oops, it's already a feature mostly.

**Comment by akarshjain40** [comment]
How we can exclude fields such as systemd_slice

**Comment by hookenz** [comment]
@akarshjain40 - Use filters

See: https://github.com/elastic/beats/blob/v5.0.0-alpha4/libbeat/_meta/config.full.yml#L61-L72
