### ISSUE TITLE
Type mapping 

### ISSUE THREAD

**Issue by hookenz** [mheese/journalbeat#103]
The `type` field is hard coded to the TYPE field from the journal if present or `jb.config.DefaultType`
i.e. beats/journalbeat.go

    if _, ok := event["type"].(string); !ok {
        event["type"] = jb.config.DefaultType
    }

I'd like to be able to override this further.  filebeat appears to do that by the document_type under filebeat.prospectors.

Since journalbeat is a single log of all service outputs, it makes sense to specify the type field by service name and if it appeared to come from syslog then type would be "syslog", then fallback to the defined DefaultType in the configuration file.

e.g. An apache server started with an apache2.service or nginx started from nginx.service could have a mapping defined like this:
````
journalbeat:
  document_types:
    apache2: apache
    nginx: nginx
````
Which means the apache2.service would set the type field to "apache" and nginx to "nginx".
This makes further processing in logstash or in elasticsearch much easier.  We can simply filter on all nginx logs with `type:nginx` rather than searching for specific units or doing extra filtering in logstash to add a type field.

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
