### ISSUE TITLE
Support for multiple monitors/cursors

### ISSUE THREAD

**Issue by jalaziz** [mheese/journalbeat#105]
I know this would require a decent amount of refactoring, but it would be nice if journalbeat could support multiple monitors.

The reasoning behind this request is:
1. It would allow user-defined tags and fields to the results of each cursor
2. It would allow decoding json messages individually (similar to filebeat)
3. It would simplify complex filtering (similar to filebeat's `include_lines`)
4. Since a cursor can only be read from one thread, this could potentially improve performance if matching many units or identifiers (just a theory)

I know some filtering and tagging can be accomplished through processors, but this could potentially improve things by applying some filters at the cursor level (e.g. log priority).

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
