### ISSUE TITLE
Journalbeat <= 5.5.0 incompatibility with CoreOS Stable >= 1465.6

### ISSUE THREAD

**Issue by eunomie** [mheese/journalbeat#106]
Hi,

I'm running several clusters on CoreOS stable. On all the servers I have a journalbeat that sends logs to an ELK. It works well until the last CoreOS stable upgrade, to `1465.6.0` (before was `1409.9.0`).
CoreOS is a system with an automatic upgrade. So all the servers, one by one, upgraded to the last stable.

Since the upgrade, I have a lot of problems with logs:

- no logs are sent (full of `INFO No non-zero metrics in the last 30s`)
- logs are corrupted with utf8 chars, even in field names (see below for all details)

I was running a `v5.1.2-12-g12f42c2` docker image of journalbeat (because of some changes in the way cursor and queue files are managed).

I have reproduce all cases using vagrant coreos boxes and here are the results:

CoreOS version | Journalbeat version | Status
----------------------|----------------------------|----------
1406.9 | v5.1.2-12-g12f42c2 | Logs are sent and no corruption visible
1406.9 upgraded to 1465.6 | v5.1.2-12-g12f42c2 | Logs are sent but data corrupted (no corruption in journalctl)
1406.9 upgraded to 1465.6 | v5.5.0 | no log
1465.6 | v5.1.2-12-g12f42c2 | no log
1465.6 | v5.5.0 | no log
1465.6 | master (docker image) | no log since the queue is empty
1465.6 | master (binary, no docker image) | logs are sent and no corruption visible

There's some strange behaviors when their is messages in the queue or not. In the 1465.6 + docker master I guess the messages in the queue was sent, then no messages are sent. But if I stop the docker and run the same version without docker (the binary by itself) the messages in the queue are sent and all the following.

ATM I haven't really dig into the docker image to understand why it doesn't work as expected.

If you need any other information just ask, I can reproduce all the previous cases.

Here are some details, bad messages, etc.

<details>
<summary>Bad log received, json</summary>

```json
{
  "@timestamp": "2017-08-19T15:31:46.202Z",
  "beat": {
    "hostname": "32cdf60abc94",
    "name": "journalbeat",
    "version": "5.2.1"
  },
  "boot_id": "dd75fa93b0224012920cf343658b8777",
  "cap_effective": "3fffffffff",
  "comm": "docker",
  "exe": "/run/torcx/unpack/docker/bin/docker",
  "fields": {
    "env": "staging",
    "host": "core-1",
    "project": "sqsc"
  },
  "gid": "0",
  "hostname": "core-1.staging",
  "input_type": "journal",
  "machine_id": "e592560b8cd943d7a3677fcc4490fd4b",
  "message": "D, [2017-08-19T15:31:46.201528 #1] DEBUG -- : [8495fa9d-04cc-4c83-b978-e0cc9654d824]   \u001b[1m\u001b[35m (1.1ms)\u001b[0m  \u001b[1m\u001b[34mSELECT COUNT(*) FROM \"projects\" WHERE \"projects\".\"infra_status\" = $1\u001b[0m  [[\"infra_status\", \"ok\"]]",
  "pid": "2364",
  "priority": "6",
  "selinux_context": "system_u:system_r:kernel_t:s0",
  "syslog_facility": "3",
  "syslog_identifier": "docker",
  "systemd_cgroup": "/system.slice/system-web.slice/web@2.service",
  "systemd_invocation_id": "733b23f150c14f308f165c8f873afd07",
  "systemd_slice": "system-web.slice",
  "systemd_unit": "web@2.service",
  "transport": "stdout",
  "type": "journal",
  "uid": "0",
  "\ufffd\u0002\u0000\u0000\u0000\u0000\u0000\u0000\ufffd*_cmdline": "/run/torcx/bin/docker run --rm --hostname web --\u000b\u0000\ufffd\u001ep 3000:3000 -e NOMAD_PUBLIC_STATUS_SECRET -e \n\u0000\ufffd\u0007_KEY_BASE -e RAILS_ENV\r\u0000\ufffdLOG_TO_STDOUT\u0017\u0000\ufffd\nMAX_THREADS -e AWS_REGION\u000e\u0000aACCESS^\u0000$ID\u0015\u0000\u0003s\u0000\u0006\u001c\u0000\u0002\ufffd\u0000\ufffd\u0006RVER_URL -e INTERNAL_\u0017\u0000kNOTIFY\u0015\u0000dGITHUBH\u0000\u0003\u000e\u0000\u0002d\u0000\ufffd\r -e ECD_ADDR -e DATABASE_HOS\ufffd\u0000\u0005\u0011\u0000qUSERNAM\u0000\u0001\u0005\u0015\u0000qPASSWOR\ufffd\u0000uELASTIC:\u0000\ufffdTRAVIS_SYNC_SN\ufffd\u0000\u0002i\u0001\n\ufffd\u0000DETCD\ufffd\u0000tROLLBAR\ufffd\u0000ATOKE)\u0001\u0002p\u0001\ufffdLOG_LEVE\u0000\u0001\ufffdNO_CONTRACT[\u0000\u0002#\u0000\u0001[\u0000\u0001\ufffd\u0001qIC_FILE\u001c\u0000\ufffdMANAGEDB_HOOKl\u0000\u0005\u0015\u0000\u0003\ufffd\u0000TFRONT\u001d\u0000\ufffdCONSUL_CLIENT\u001d\u0001\ufffd1.dkr.ecr.eu-west-1.amazonaws.com/sqsc:staging-latest"
}
```
</details>

<details>
<summary>Error visible in logstash</summary>

```
Aug 19 11:25:44 core-3.monitoring docker[1345]: [2017-08-19T11:25:44,734][WARN ][logstash.outputs.elasticsearch] Failed action. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"journalbeat-2017.08.19", :_type=>"journal", :_routing=>nil}, 2017-08-19T11:25:43.673Z 2327ee2e843c %{message}], :response=>{"index"=>{"_index"=>"journalbeat-2017.08.19", "_type"=>"journal", "_id"=>"AV36Pd1uAajMKwwarNKX", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"object field starting or ending with a [.] makes object resolution ambiguous: [.\u0005\u0000\u0000\u0000\u0000\u0000\u0000�\u0018message]"}}}}}
```

</details>

<details>
<summary>Fields in kibana</summary>

![screenshot from 2017-08-25 11-18-30](https://user-images.githubusercontent.com/1542321/29707903-333fd112-8987-11e7-8a5a-e4b45cfee5b9.png)

</details>

**Comment by eunomie** [comment]
A docker image based on `stretch-slim` seems to fix the problem of not sending logs.

**Comment by eunomie** [comment]
A version based on the current `master` 2989e18a4e60c7457340e0bf57c5562a241d354c based on `debian:stretch-slim` is available at  [`eunomie/journalbeat:v5.5.0-8-g4548b76`](https://hub.docker.com/r/eunomie/journalbeat/tags/).

**Comment by mheese** [comment]
@eunomie thanks for the thorough research! 👍 ... I have a suspicion that this will also fix some issues that other people have been describing.

Apart from your issue at hand, changing to Debian 9 sounds like a reasonable thing to do anyway.

**Comment by eunomie** [comment]
I've deployed the version master-debian 9 on my servers and ATM it works as expected.

One change between the both CoreOS version is the kernel version, from 4.11.12 to 4.12.7. Maybe it's related, but I don't know how. I'll see if I can fill an issue on CoreOS, maybe it's related to one component they change.

**Comment by euank** [comment]
I gave my guess for why this happened on the [coroes/bugs issue](https://github.com/coreos/bugs/issues/2121).

I'll point out that if my guess is correct, this should also impact Fedora, which has the same configuration, and probably a number of other distros.

**Comment by mheese** [comment]
As PR #107 is merged, please confirm this is working ... then we can close this

**Comment by eunomie** [comment]
Sorry for the late feedback. I upgrade some servers to the new version and everything is ok on my side.
Thanks for this version :+1: 
I guess you can close this issue.
