### ISSUE TITLE
Support for beats 6.0?

### ISSUE THREAD

**Issue by joshuabaird** [mheese/journalbeat#110]
I'm looking for the `ttl` option on the logstash output discussed here:

https://github.com/elastic/beats/pull/4343

It looks like this was merged into beats:master, but isn't targeted for release until 6.0 (which is currently alpha).  Once 6.0 has been released, are there plans to upgrade journalbeat to use 6.0+ so that we can take advantage of this new `ttl` option?

**Comment by nicorevin** [comment]
Yes there are :) I hope I will find some time soon to look closer to what has changed in the 6.x branch to better align with their release cycle.

**Comment by joshuabaird** [comment]
Great - thank you!

**Comment by kaarolch** [comment]
@joshuabaird if you use the 6.0.0-beta1 from release the ttl was already add to it.

**Comment by joshuabaird** [comment]
@kaarolch Yeah, I'm just not exactly sure how to rebase journalbeats with 6.0.0-beta1.

**Comment by jstoja** [comment]
@nicorevin @mheese Any plan to support 6.x ? It's now the current release and I think there are some breaking changes in the beats protocol.

**Comment by pontostroy** [comment]
libbeat > 6.0 has http endpoind metrics.
Are there any plans for migrating to the new libbeat?

**Comment by nrvnrvn** [comment]
There are plans, even some early WIP, but no time unfortunately...

**Comment by jwitko** [comment]
@nrvnrvn looks like there is a pull request that functions with ES 6.x if you'd care to review

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
