### ISSUE TITLE
libbeats version

### ISSUE THREAD

**Issue by c4milo** [mheese/journalbeat#113]
I'm seeing this message in my ES cluster, could it be caused by journalbeat being compiled against libbeat 5.5.1 instead of 5.5.2? I'm running ES 5.5.2 and Kibana 5.5.2 as well. 

arch[21687]: [2017-09-06T15:41:47,493][ERROR][o.e.x.w.t.a.g.TransportGetWatchAction] [ALg2MhD] failed to
arch[21687]: java.lang.IllegalStateException: watch store not started
arch[21687]: at org.elasticsearch.xpack.watcher.watch.WatchStore.ensureStarted(WatchStore.java:367) ~[?:
arch[21687]: at org.elasticsearch.xpack.watcher.watch.WatchStore.get(WatchStore.java:153) ~[?:?]
arch[21687]: at org.elasticsearch.xpack.watcher.WatcherService.getWatch(WatcherService.java:158) ~[?:?]
arch[21687]: at org.elasticsearch.xpack.watcher.transport.actions.get.TransportGetWatchAction.masterOper
arch[21687]: at org.elasticsearch.xpack.watcher.transport.actions.get.TransportGetWatchAction.masterOpe

### journalbeat log

```
Sep 06 15:53:21 localhost.localdomain assembly-journalbeat[30813]: "beat": {
Sep 06 15:53:21 localhost.localdomain assembly-journalbeat[30813]: "hostname": "assembly-journalbeat",
Sep 06 15:53:21 localhost.localdomain assembly-journalbeat[30813]: "name": "journalbeat",
Sep 06 15:53:21 localhost.localdomain assembly-journalbeat[30813]: "version": "5.5.1"
Sep 06 15:53:21 localhost.localdomain assembly-journalbeat[30813]: },
Sep 06 15:53:21 localhost.localdomain assembly-journalbeat[30813]: "boot_id": "3d0b615ab00f4a94b3b558d77358fbd8",
Sep 06 15:53:21 localhost.localdomain assembly-journalbeat[30813]: "gid": "0",
Sep 06 15:53:21 localhost.localdomain assembly-journalbeat[30813]: "hostname": "localhost.localdomain",
Sep 06 15:53:21 localhost.localdomain assembly-journalbeat[30813]: "machine_id": "baa080ae100141b7b1be54105120f6f3",
```

**Comment by mheese** [comment]
I'm not sure what that means ... but we should pull in and rebuild against the `5.5.2` anyway.

**Comment by nicorevin** [comment]
@c4milo it can hardly be an issue. According to the [elastic compatibility matrix](https://www.elastic.co/support/matrix#matrix_compatibility) any beat of version `5.5.0` is compatible with version `5.5.2` of ES.

**Comment by brucemartins** [comment]
am I reading the repo incorrectly ? as it seems it's pulling in libbeat 5.4.x not 5.5 , really based on the commit comments

**Comment by nicorevin** [comment]
All release versions align with the libbeat versions. For instance https://github.com/mheese/journalbeat/blob/v5.5.2/vendor/vendor.json#L58
