### ISSUE TITLE
Possible performance issues?

### ISSUE THREAD

**Issue by joshuabaird** [mheese/journalbeat#114]
I'm using journalbeat to send logs to a cluster of Logstash instances.  My logstash instances output to a remote syslog (via UDP) host.  My syslog host is seeing delays of ~10-20minutes in some cases and I'm trying to determine where my bottleneck is.  I have a feeling it's Logstash, but wanted to get the opinion of others.

Here is a snippet from my journalbeat logs:

```
2017/09/06 19:38:56.644823 metrics.go:39: INFO Non-zero metrics in the last 30s: libbeat.logstash.publish.read_bytes=120 libbeat.logstash.publish.write_bytes=103337
2017/09/06 19:39:26.644780 metrics.go:39: INFO Non-zero metrics in the last 30s: libbeat.logstash.call_count.PublishEvents=1 libbeat.logstash.publish.read_bytes=126 libbeat.logstash.publish.write_bytes=104989 libbeat.logstash.published_and_acked_events=2048 libbeat.publisher.messages_in_worker_queues=2048 libbeat.publisher.published_events=2048
2017/09/06 19:39:56.644786 metrics.go:39: INFO Non-zero metrics in the last 30s: libbeat.logstash.publish.read_bytes=156 libbeat.logstash.publish.write_bytes=133391
2017/09/06 19:40:26.644786 metrics.go:39: INFO Non-zero metrics in the last 30s: libbeat.logstash.call_count.PublishEvents=1 libbeat.logstash.publish.read_bytes=114 libbeat.logstash.publish.write_bytes=94444 libbeat.logstash.published_and_acked_events=2048 libbeat.publisher.messages_in_worker_queues=1 libbeat.publisher.published_events=1
2017/09/06 19:40:56.644781 metrics.go:39: INFO Non-zero metrics in the last 30s: libbeat.logstash.publish.read_bytes=132 libbeat.logstash.publish.write_bytes=112444
2017/09/06 19:41:26.644797 metrics.go:39: INFO Non-zero metrics in the last 30s: libbeat.logstash.call_count.PublishEvents=2 libbeat.logstash.publish.read_bytes=126 libbeat.logstash.publish.write_bytes=102136 libbeat.logstash.published_and_acked_events=2049 libbeat.publisher.messages_in_worker_queues=4096 libbeat.publisher.published_events=4096
2017/09/06 19:41:56.644780 metrics.go:39: INFO Non-zero metrics in the last 30s: libbeat.logstash.publish.read_bytes=114 libbeat.logstash.publish.write_bytes=96867
2017/09/06 19:42:26.644782 metrics.go:39: INFO Non-zero metrics in the last 30s: libbeat.logstash.publish.read_bytes=120 libbeat.logstash.publish.write_bytes=104312
2017/09/06 19:42:56.644811 metrics.go:39: INFO Non-zero metrics in the last 30s: libbeat.logstash.call_count.PublishEvents=1 libbeat.logstash.publish.read_bytes=150 libbeat.logstash.publish.write_bytes=126644 libbeat.logstash.published_and_acked_events=2048 libbeat.publisher.messages_in_worker_queues=2048 libbeat.publisher.published_events=2048
2017/09/06 19:43:26.644880 metrics.go:39: INFO Non-zero metrics in the last 30s: libbeat.logstash.call_count.PublishEvents=1 libbeat.logstash.publish.read_bytes=150 libbeat.logstash.publish.write_bytes=127669 libbeat.logstash.published_and_acked_events=2048 libbeat.publisher.messages_in_worker_queues=2 libbeat.publisher.published_events=2
2017/09/06 19:43:56.644787 metrics.go:39: INFO Non-zero metrics in the last 30s: libbeat.logstash.publish.read_bytes=138 libbeat.logstash.publish.write_bytes=118533
```

Anything obvious in these logs that would indicate an issue?  Can someone tell me what type of performance I should expect out of Journalbeat (how many requests/second, etc).

Thanks!

**Comment by mheese** [comment]
Hmm, it doesn't strike me as a lot of events getting published. Does your application also write timestamps? What you should try to compare are application timestamp, systemd/journald timestamp, logstash receiving timestamp ... and ultimately syslog receiving timestamp.

Sorry that I can't be of bigger help here ... however, what I've seen in the past is that journald is not able to hanlde tremendous big load. That said, in my experience the error is in >90% of the cases in logstash ;)

**Comment by joshuabaird** [comment]
I didn't think so either.  Yes, it does log timestamps which is how I'm easily able to identify the lag.  What load have you seen journal not able to handle?  I don't think our load is super crazy.  Any ideas how to identify the timestamp when Logstash receives the message?  Journald is getting the messages on time for sure.

**Comment by mheese** [comment]
hm, nothing pops into my mind right now ... if I  would have to do it, I would probably resort to the ruby filter plugin (https://www.elastic.co/guide/en/logstash/current/plugins-filters-ruby.html). It's your swiss army knife when there is no solution in logstash itself :) ... the problem is that the timestamp fields are properly forwarded to logstash (as they should) ... it's always been a concern of mine that when one gets into a situation like you are in right now, one can't easily debug that

**Comment by joshuabaird** [comment]
@mheese Could you help me understand what happens when the Logstash instance that journalbeat is connected to temporarily goes down (or becomes overloaded, etc)?  Does journalbeat log the messages, and then try to send them all at once as soon as the Logstash output becomes available once again?

If this is the case, I can see where I would observe *some* lag.  My remote syslog output enforces it's OWN timestamp, meaning it adds it's own timestamp once the message arrives.  So, if journalbeat sends a log 5 minutes late, my application timestamp and the timestamp enforced by my syslog provider would be appear to be off my 5 minutes.

**Comment by nicorevin** [comment]
@joshuabaird hi! It seems very strange to see`published_and_acked_events=2048` in every metrics log line.

If the logstash goes down /gets overloaded you will see both queues (logstash's and journalbeat's) to become full. I suppose this is why you see this straight 2048/minute rate.

2048 is an internal libbeat's queue size and I suppose there is some similar limitation all the way up to syslog.

**Comment by joshuabaird** [comment]
@nicorevin Hi!  So, those metrics lines are showing that libbeat's queue is completely full?  Could this be my issue?  What happens then?  Messages get discarded?

**Comment by nicorevin** [comment]
depends on your output configuration. if you've set `max_retries: -1` then the messages will reside in the queue until the logstash/es/kafka/etc. gets unblocked and then they will be resent. Otherwise the default number of retries is 3 and then the message will be discarded.

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
