### ISSUE TITLE
`journalbeat` running under Habitat is not working

### ISSUE THREAD

**Issue by smartb-pair** [mheese/journalbeat#115]
Steps to reproduce (using an Ubuntu 16.04 VM):

Install Habitat:
```
curl -sL https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash -s
```
Install the `smartb/journalbeat` Habitat package:
```
curl -sL https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash -s
```
Ensure `journalbeat` can execute:
```
hab pkg exec smartb/journalbeat journalbeat -version
```
Repeat the above command but with `-e` or similar flags to test a `journalbeat.yml` config in your working directory. You should see that, although the program starts, no logfiles are sent.

We think that this is due Habitat's dependency isolation model - the `smartb/journalbeat` package depends on `core/systemd` to get system headerfiles, rather than an Ubuntu package. Any thoughts on how to proceed with debugging/fixing this would be very helpful.

**Comment by mheese** [comment]
@smartb-pair the 1st and 2nd command line look the same to me ... (copy&paste mistake?)

not sure how you are installing (or what habitat actually is) journalbeat, but please make sure you are not running into the same issue that CoreOS users have which might be the case with a recent Ubuntu version as well ... see #106 and #107 respectively for the fix ... somebody pointed to this on the CoreOS bugs list (https://github.com/coreos/bugs/issues/2121#issuecomment-324993391), and at the end of the day it might boil down to missing LZ4 or similar?

Anyway, happy to try to reproduce it when you give me that 2nd command line!

**Comment by bixu** [comment]
Hey, sorry about that @mheese - the command would be:
```
hab pkg install smartb/journalbeat
```
You can find out more about Habitat at http://habitat.sh

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
