### ISSUE TITLE
Switch docker builds to multi-stage builds

### ISSUE THREAD

**Issue by mheese** [mheese/journalbeat#126]
Multi-stage builds are finally natively possible in docker: https://docs.docker.com/engine/userguide/eng-image/multistage-build/

**Comment by loosi** [comment]
It is actually easy moving it to multi-stage builds, I did it last week. IMHO you can remove the whole makefile and multiple dockerfiles while just keeping a single dockerfile. With my docker I was unable to use the config.yml from the docker directory (some weird `docker build` excludes, so you may have to move into the main folder or another subfolder permanently. 
I can create a pull request if you like to.

**Comment by mheese** [comment]
@loosi yes please! I was hoping that we can get rid of a lot of the build stuff

**Comment by loosi** [comment]
ok. I will clean up some dev stuff for me and then make a pull request. I actually had to use debian (o whatever you want) as base image for the second stage of the build since it wont work with musl glibc (see #92)

**Comment by loosi** [comment]
I opened up a pull request #127

**Comment by CpuID** [comment]
> @loosi yes, I saw it ... I promise I'll take care of it in the next days ... sorry for the delay

*bump* :)
