### ISSUE TITLE
Docker tag missing for v5.6.0

### ISSUE THREAD

**Issue by leedm777** [mheese/journalbeat#129]
I see a tag in GitHub for v5.6.0, but no corresponding tag on Docker Hub. Can you push that build to Docker Hub?

**Comment by mheese** [comment]
yes ... I _promise_ I'll take care of it in the next days ... sorry for the delay

**Comment by leedm777** [comment]
Thanks!

**Comment by jstoja** [comment]
Might be nice to add it to travis :)

**Comment by alexef** [comment]
thanks!

**Comment by jstoja** [comment]
hey @mheese any news on that :) might be a good idea to add it to the travis file so it's automatically pushed !

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
