### ISSUE TITLE
Strip ANSI color codes from journal output

### ISSUE THREAD

**Issue by bonovoxly** [mheese/journalbeat#134]
Hi,

This may be configurable elsewhere (I'm digging around with the `SYSTEMD_COLORS=0` environment variable), but would it be possible to add the ability to strip ANSI color codes from the journal message?

**Comment by bonovoxly** [comment]
https://github.com/mheese/journalbeat/pull/135

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
