### ISSUE TITLE
journalbeat monitoring (telemetry)

### ISSUE THREAD

**Issue by shellshock1953** [mheese/journalbeat#138]
Any options to get metrics from journalbeat, to be able to get real-time monitoring (Netdata, statsD, etc?)

**Comment by jsuchenia** [comment]
Maybe we can change current metrics to prometheus format and expose them over http endpoint?

**Comment by pontostroy** [comment]
I am write very ugly, but working libbeat metrics http sharing, maybe someone can rewrite it in better way.
https://github.com/mheese/journalbeat/compare/master...pontostroy:master.diff

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
