### ISSUE TITLE
Getting the logs of the host in Container

### ISSUE THREAD

**Issue by Vad1mo** [mheese/journalbeat#145]
We have very simple hosts that only run Docker. (We don't won't to install there anything else.) Thats why everything should be in containers. 

Now we would like to run Journalbeat in a container but access/get the journald logs of the **host**. We would then run Journalbeat container on each node and forward the logs to the dedicated container. (Network is setup on container level)

However I am not sure if that is possible to run journalbeat in a container and have access to the hosts systemd/journal.

**Comment by mheese** [comment]
@Vad1mo yes, you should be able to mount in the right paths into the container and get what you want. I have done it before, however, I don't have a command line for you from the top of my head right now. When I remember correctly the important thing is to mount in the systemd/journald sockets and the `/run` hierarchy (or similar). Unfortunately, you'll have to play with it a bit.

Somebody here using Fedora/RHEL Atomic Host or CoreOS should be able to help out better.

**Comment by loosi** [comment]
our lines working for ubuntu from a compose file (swarm usage)
```    
- /var/log/journal:/var/log/journal
- /etc/machine-id:/etc/machine-id  
- /etc/hostname:/etc/hostname:ro
```

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
