### ISSUE TITLE
How to specify kibana host when loading templates?

### ISSUE THREAD

**Issue by NiceGuyIT** [mheese/journalbeat#147]
`setup.kibana` is used in other beats but doesn't work for journalbeat. I tried everything I could think of to specify `setup.kibana.host` and the only way I could get it to work is to hard code the host in `vendor/github.com/elastic/beats/libbeat/setup/kibana/config.go`.

Is an alternate Kibana URL supported?

Environment
-------------
My environment has all the beats going through Logstash which means the templates are not loaded automatically. To load the templates, the beats are run with `output.logstash=false` and `output.elasticsearch=true` with URLs to both Kibana and Elasticsearch, both on different hosts (containers). Here's an example command to load the filebeat templates.
```
filebeat setup -e -v --template \
    -E setup.template.overwrite=true \
    -E output.logstash.enabled=false \
    -E output.elasticsearch.enabled=true \
    -E output.elasticsearch.hosts='["elasticsearch.localdomain:9200"]' \
    -E setup.kibana.enabled=true \
    -E setup.kibana.host="kibana.localdomain:5601"
```

Versions
---------

* openSUSE Leap 42.3
* elasticsearch 6.2.4-1
* logstash 6.2.4-1
* journalbeat version 5.6.9 (amd64), libbeat 5.6.9
* go version go1.9.4 linux/amd64

**Comment by mickymiek** [comment]
Same issue here. Even with `setup.kibana.host` set to my kibana instance, I'm getting this error: `beat.go:344: CRIT Exiting: Error importing Kibana dashboards: fail to create the Kibana loader: Error creating Kibana client: fail to get the Kibana version:HTTP GET request to /api/status fails: fail to execute the HTTP GET request: Get http://localhost:5601/api/status: dial tcp [::1]:5601: connect: cannot assign requested address. Response: .`.

**Comment by NiceGuyIT** [comment]
@mickymiek Add the host to the source and rebuild.

```diff
diff --git a/vendor/github.com/elastic/beats/libbeat/setup/kibana/config.go b/vendor/github.com/elastic/beats/libbeat/setup/kibana/config.go
index 24df8a2..a1aae38 100644
--- a/vendor/github.com/elastic/beats/libbeat/setup/kibana/config.go
+++ b/vendor/github.com/elastic/beats/libbeat/setup/kibana/config.go
@@ -19,7 +19,7 @@ type kibanaConfig struct {
 var (
        defaultKibanaConfig = kibanaConfig{
                Protocol: "http",
-               Host:     "",
+               Host:     "Kibana",
                Path:     "",
                Username: "",
                Password: "",
```

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
