### ISSUE TITLE
File descriptors don't released?

### ISSUE THREAD

**Issue by OlegYankovic** [mheese/journalbeat#148]
Looks like journalbeat opens every log file from /var/log/journal/ as I can see it from file descriptors (/proc/{pid}/fd). And file descriptors don't released after rotating of journald. We still have descriptors to files that was rotated(deleted).
I use journalbeat at a system with huge logs generation and it leads to exceeding of descriptors limits through some time.

**Comment by mheese** [comment]
@OlegYankovic sounds like something we need to address with https://github.com/coreos/go-systemd , as we're using this library to interact with journald. We might also be using the library in a wrong way. I currently don't see how though.

**Comment by OlegYankovic** [comment]
Some additional observation. Descriptors do released if journal rotation is started at the moment when there are no events for journalbeat to publish. But when, for example, journalbeat started on fresh system with several gigabytes of logs and journal rotation is started (I initiate it with command "journalctl --vacuum-size"), then journal files from /var/log/journal/ is deleted but descriptors to this files still exist in /proc/{pid}/fd/.

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
