### ISSUE TITLE
Dockerhub image for v5.6.9

### ISSUE THREAD

**Issue by cparmar** [mheese/journalbeat#149]
Can we get an image pushed to Docker Hub for v5.6.9?

**Comment by mikafouenski** [comment]
Now in docker hub you can setup automatic build to build it every time this Github repo is updated. :)

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
