### ISSUE TITLE
Incoroporate vendoring

### ISSUE THREAD

**Issue by nicorevin** [mheese/journalbeat#15]

**Comment by mheese** [comment]
yeah ... badly needed, I agree ... my time for this project is unfortunately sparse at the moment. PRs are always welcome!

**Comment by mheese** [comment]
@nicorevin, I added you as a collaborator ... please feel free to merge (also any other features that you see fit) ... I'm not going to be able to work on this at least for the next 4 weeks as I have competing priorities unfortunately

**Comment by siddharthist** [comment]
Closed in #18

**Comment by nicorevin** [comment]
Thank you @mheese. I think I will still create PRs for any major changes.
