### ISSUE TITLE
Support longer lines

### ISSUE THREAD

**Issue by berndwinterstein** [mheese/journalbeat#150]
Is there a way to configure journalbeat to preserve longer lines for json logs?

**Comment by hookenz** [comment]
@berndwinterstein - can you explain what's not working a bit better?   Line length hasn't been a problem for me.  I've put quite long lines of json (single line entry) into the systemd journals and not had it truncate.  i.e. I actually write json data into the message not text.

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
