### ISSUE TITLE
metadata version does not appear to get set

### ISSUE THREAD

**Issue by opoplawski** [mheese/journalbeat#152]
Just trying out journalbeat on EL7.5.  I have a beats -> logstash -> elasticsearch pipeline
```
input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
  }
}
```
With filebeat I get an index like filebeat-6.4.1-2018.09.27.  With journalbeat I get journalbeat-%{[@metadata][version]}-2018.09.27 - so it looks like it is not transmitting the version metadata for some reason?

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
