### ISSUE TITLE
Feature Request: Prometheus Monitoring Endpoint for Journalbeat

### ISSUE THREAD

**Issue by anandsinghkunwar** [mheese/journalbeat#158]
I'd like to make a feature request for a prometheus endpoint for journalbeat for the purpose of monitoring its metrics via prometheus.

**Comment by nrvnrvn** [comment]
Hi!
I believe it is better to address this request to elastic. Since recently they’ve released their official journalbeat.
https://www.elastic.co/guide/en/beats/journalbeat/current/journalbeat-overview.html
