### ISSUE TITLE
type: unknown

### ISSUE THREAD

**Issue by alejojo** [mheese/journalbeat#16]
Hi there,

looking at the example file `journalbeat.yml` there is no option to add a type, and when loading kibana it shows a: `unkown`
With filebeat that was configured by `document_type`. I placed it everywhere, flushed db, and launched journalbeat but it does not recognize it.

**Comment by nicorevin** [comment]
We had to hardcode it [at the end](https://github.com/mheese/journalbeat/blob/4489182d769a847bfc9e449b2a41b6ad5579d3f0/beat/convert.go#L104) of `func MapStrMoveJournalMetadata` to make it work:
```m["type"] = "journal"```

It is worth adding it to the config I think. What do you think, @mheese?

**Comment by mheese** [comment]
can't you add this with the fields option? My colleague was mentioning something similar this week, and I didn't completely understand what the issue is with this?

He was mentioning that this breaks logstash as well? 

I was thinking that it might be better to use the log type of the actual journal input log type? (kernel / syslog / journal) 

@alejojo, @nicorevin, input welcome ... I'm open to suggestions ... maybe hardcoding is a good idea after all

**Comment by alejojo** [comment]
Hi @nicorevin and @mheese 

I am not an expert in ELK (just started to use it) but, I think to use journalbeat.yml would be better since is how beats configurations runs.

Cheers,

**Comment by mheese** [comment]
@alejojo that's what I meant by "fields" option ... are you able to get the type field by adding it in that section? It's described in the example yaml in the repo

**Comment by nicorevin** [comment]
`fields` go under `fields_dest` as a nested dict unless you don't define `fields_dest`. It must work but that's hacky.

**Comment by slavikvin** [comment]
Hi, can you provide working config example for changing type field, can't get it working, help please.

**Comment by nicorevin** [comment]
Well, I can't get all this `fields` stuff working at all now.
I receive this:

```sh
$ sudo ./journalbeat
panic: reflect.Set: value of type common.MapStr is not assignable to type *common.MapStr

goroutine 1 [running]:
panic(0x8acd00, 0xc8201b3d20)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
reflect.Value.assignTo(0xa2cfe0, 0xc8201b8f30, 0x15, 0xa7da60, 0xb, 0xa2ac40, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:2164 +0x3be
reflect.Value.Set(0xa2ac40, 0xc8200930d8, 0x196, 0xa2cfe0, 0xc8201b8f30, 0x15)
        /usr/local/go/src/reflect/value.go:1334 +0x95
github.com/mheese/journalbeat/vendor/github.com/urso/ucfg.reifyGetField(0xc8201b8ab0, 0xa65ad8, 0x6, 0xa81400, 0x8, 0xa610d8, 0x1, 0x0, 0x0, 0x0, ...)
        github.com/mheese/journalbeat/vendor/github.com/urso/ucfg/reify.go:161 +0x252
github.com/mheese/journalbeat/vendor/github.com/urso/ucfg.reifyStruct(0xa65ad8, 0x6, 0xa81400, 0x8, 0xa610d8, 0x1, 0x0, 0x0, 0xa1b7a0, 0xc820093040, ...)
        github.com/mheese/journalbeat/vendor/github.com/urso/ucfg/reify.go:122 +0xc22
github.com/mheese/journalbeat/vendor/github.com/urso/ucfg.reifyMergeValue(0xa65ad8, 0x6, 0xa81400, 0x8, 0xa610d8, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/mheese/journalbeat/vendor/github.com/urso/ucfg/reify.go:298 +0x1026
github.com/mheese/journalbeat/vendor/github.com/urso/ucfg.reifyGetField(0xc8201b8150, 0xa65ad8, 0x6, 0xa81400, 0x8, 0xa610d8, 0x1, 0x0, 0x0, 0x0, ...)
        github.com/mheese/journalbeat/vendor/github.com/urso/ucfg/reify.go:156 +0x1aa
github.com/mheese/journalbeat/vendor/github.com/urso/ucfg.reifyStruct(0xa65ad8, 0x6, 0xa81400, 0x8, 0xa610d8, 0x1, 0x0, 0x55d400, 0x98ebc0, 0xc8200a4a00, ...)
        github.com/mheese/journalbeat/vendor/github.com/urso/ucfg/reify.go:122 +0xc22
github.com/mheese/journalbeat/vendor/github.com/urso/ucfg.reifyInto(0xa65ad8, 0x6, 0xa81400, 0x8, 0xa610d8, 0x1, 0x0, 0xa61000, 0x98ebc0, 0xc8200a4a00, ...)
        github.com/mheese/journalbeat/vendor/github.com/urso/ucfg/reify.go:40 +0x319
github.com/mheese/journalbeat/vendor/github.com/urso/ucfg.(*Config).Unpack(0xc8201b8150, 0x87b240, 0xc8200a4a00, 0xc82014fc90, 0x1, 0x1, 0x0, 0x0)
        github.com/mheese/journalbeat/vendor/github.com/urso/ucfg/reify.go:24 +0x356
github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/common.(*Config).Unpack(0xc8201b8150, 0x87b240, 0xc8200a4a00, 0x0, 0x0)
        github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/common/config.go:34 +0xc8
github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/cfgfile.Read(0x87b240, 0xc8200a4a00, 0x0, 0x0, 0x0, 0x0)
        github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/cfgfile/cfgfile.go:53 +0x88
github.com/mheese/journalbeat/beat.(*Journalbeat).Config(0xc8200a4a00, 0xc82005e900, 0x0, 0x0)
        github.com/mheese/journalbeat/beat/journalbeat.go:75 +0x98
github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/beat.(*instance).config(0xc8200e53e0, 0x0, 0x0)
        github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/beat/beat.go:238 +0x78d
github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/beat.(*instance).launch(0xc8200e53e0, 0x0, 0x0)
        github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/beat/beat.go:296 +0xa0
github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/beat.Run(0xa7a3d0, 0xb, 0xa611e8, 0x5, 0x7f2df66f5c48, 0xc8200a4a00, 0x0, 0x0)
        github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/beat/beat.go:126 +0x6d
main.main()
        github.com/mheese/journalbeat/main.go:26 +0x7d
```

Looking into it right now

**Comment by nicorevin** [comment]
looks like journalbeat is not compatible with the latest libbeat.
Without `fields` and `field_dest` everything goes smooth.

But when I add smth like:

```yaml
input:
  fields_dest: anything
  fields:
    lol: woot
```

I get panic.
@alejojo, @mheese, @slavikvin ^

**Comment by mheese** [comment]
Thinking about this issue in the past 2 weeks, I think I'm coming to the following conclusion:
- my idea of not setting the type was that different journal inputs could set their own type
- however, that is contradictory to what common practice is within the libbeat / ELK world
- nothing prevents the input from adding an additional field that can be used in further processing with logstash

therefore: we should add a default 'type' field that can be configured in the yaml config file, or if not present default to "journal"

@alejojo @nicorevin do you guys want to do a PR for that? (because I assume you have the working code handy for that anyway)

**Comment by nicorevin** [comment]
I will make a PR shortly.
