### ISSUE TITLE
Simplify build instructions

### ISSUE THREAD

**Issue by siddharthist** [mheese/journalbeat#22]
With this error:
```
package github.com/garyburd/redigo: no buildable Go source files in /go/src/github.com/garyburd/redigo
```
and it's correct: https://github.com/garyburd/redigo

**Comment by siddharthist** [comment]
I get the same error on https://github.com/mheese/go-systemd, and it's also correct. Looks like the installation instructions need to be fixed.

**Comment by nicorevin** [comment]
Just run `go get -d` with what you've mentioned. I hope those instructions will soon become redundant - #15.

**Comment by siddharthist** [comment]
@nicorevin It's not even necessary to do that, you can just
```
cd $GOPATH/src/github.com/mheese/journalbeat
go get .
go build .
```

**Comment by nicorevin** [comment]
@siddharthist I'm using my fork with vendor folder so i just skip the `go get` step.

**Comment by mheese** [comment]
yes, exactly ... the vendoring is actually quite important ... @nicorevin would you mind merging your PR and update the README as well?
