### ISSUE TITLE
imported and not used: "github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/common"

### ISSUE THREAD

**Issue by erikswanson** [mheese/journalbeat#27]
I'm getting unused import errors when trying to 'go get' this project in a clean GOPATH:

    + go get github.com/mheese/journalbeat
    # github.com/mheese/journalbeat/beat
    src/github.com/mheese/journalbeat/beat/config.go:18: imported and not used: "github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/common"
    src/github.com/mheese/journalbeat/beat/journalbeat.go:24: imported and not used: "github.com/mheese/journalbeat/vendor/github.com/elastic/beats/libbeat/common"

**Comment by marclennox** [comment]
Same here.

**Comment by nicorevin** [comment]
https://github.com/mheese/journalbeat/commit/c25d8831f9621148aa266314074b5f2a93aed93c
