### ISSUE TITLE
Run inside docker on CoreOS?

### ISSUE THREAD

**Issue by marclennox** [mheese/journalbeat#28]
Has anyone tried and been successful running this in a docker container on CoreOS to collect the CoreOS machine's journal logs and ship to ELK?

**Comment by nicorevin** [comment]
I recommend running it on CoreOS uncontainerized not to couple to docker which is prone to fail frequently even with latest stable CoreOS releases...

**Comment by marclennox** [comment]
Thanks @nicorevin, do you have any hints on how to install and run directly on CoreOS?

**Comment by nicorevin** [comment]
cloud-config is the simplest and straightforward solution - https://coreos.com/os/docs/latest/cloud-config.html#writefiles.

**Comment by marclennox** [comment]
Right, but is it as simple as just copying a file into place and making it executable, or would I need to install golang on CoreOS, which kind of goes contrary to how CoreOS is designed.

**Comment by nicorevin** [comment]
You need:
1. journalbeat binary
2. journalbeat config
3. systemd unit file

**Comment by marclennox** [comment]
OK, that sounds easy.  Are there pre-compiled binaries for journalbeat?  I tried building from source but had issues...  I will give it another shot, thanks @nicorevin

**Comment by nicorevin** [comment]
No precompiled binaries yet. But this will change in the nearest future I hope.

**Comment by nicorevin** [comment]
@marclennox please follow #19 Binarly releases are to come shortly :)

**Comment by eghobo** [comment]
@marclennox any luck with running journalbeat inside Docker container on top of CoreOS? we run everything under Kubernetes, so we need containers. @nicorevin which release binary should work at CoreOS? which files journalbeat watching for?
