### ISSUE TITLE
Filtering services (for log input)

### ISSUE THREAD

**Issue by AndriiOmelianenko** [mheese/journalbeat#3]
Hello,

Do you expect to have feature to filter services, from which you want to collect logs?

As I understand - right now all the logs from journald is transfered via `Journalbeat`, 
and it'll be great to have possibility to limit it for only logs from `docker`, for example.

**Comment by mheese** [comment]
Yes, that is planned. But thanks for actually opening a ticket for that. The functionality is already in the golang systemd/journald library, so it shouldn't be too hard to implement.

Are you imagining it similarly to the `journalctl` functionality I assume? At least that is what I had in mind.

**Comment by AndriiOmelianenko** [comment]
@mheese great news, thanks for update.
yes, filtering similar to `journalctl -u docker.service`

**Comment by jagguli** [comment]
+1 I'd like to use journalbeat instead of filebeat for nginx logs

https://gist.github.com/pcolazurdo/4538923

**Comment by nicorevin** [comment]
Why not use [`filters`](https://github.com/elastic/beats/blob/v5.0.0-alpha4/libbeat/_meta/config.full.yml#L61-L72) (`processors` since `alpha5`):
```yaml
filters:
  - drop_event:
      when:
        not:
          equals:
            journal.systemd_unit: ${DESIRED_SERVICE}
```
See more https://www.elastic.co/guide/en/beats/filebeat/master/configuration-processors.html

**Comment by jagguli** [comment]
That's dropping at the server side?
