### ISSUE TITLE
FIM

### ISSUE THREAD

**Issue by elvarb** [mheese/journalbeat#32]
It says in the project description that this project is planned to be common source for FIM. What are the details regarding that plan?

**Comment by mheese** [comment]
@elvarb, the idea is to use the systemd messages incoming from the kernel audit subsystem to monitor file changes (that requires it to be configured to monitor files though). We can then check against previously calculated checksums to see if a violation is in place and generate or enrich a message.

I currently don't need this, but it will probably come down the road in the next 6-12 months again, and I will probably start working on it then.

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
