### ISSUE TITLE
Outputs to queuing systems?

### ISSUE THREAD

**Issue by froztbyte** [mheese/journalbeat#33]
Are there presently any kind of outputs to queueing systems (the likes of RabbitMQ) available in `journalbeat`?

If not, would you consider facilitating them (should anything custom be necessary) when https://github.com/elastic/beats/issues/581 is solved?

**Comment by nicorevin** [comment]
Basically `journalbeat` is using `libbeat` for output. So any outputs currently available [here](https://github.com/elastic/beats/blob/e61a22d02cce50d23b924c76060ddbb7e19a4f25/libbeat/_meta/config.full.yml#L65) can be used as the output for journalbeat.
As soon as elastic/beats#581 is accomplished  it will be available for `journalbeat` as well.
