### ISSUE TITLE
Multiline support

### ISSUE THREAD

**Issue by kinghrothgar** [mheese/journalbeat#37]
From looking at other beats, specifically filebeat, it appears that the correct place to deal with multiline logs is in the beat itself.  This will require a decent amount of code, but I believe most of the logic can be grabbed from the [here](https://github.com/elastic/beats/blob/6b7df0c1b8b820da7826aa5871de40052ecaaf80/filebeat/harvester/reader/multiline.go).

**Comment by shinespb** [comment]
Do you have any plans to implement multiline support?

**Comment by mheese** [comment]
Even though I kind of disagree with doing it in the beat, it seems to become the idiomatic way in the ELK stack to deal with things as early on as possible. We should do it.

**Comment by theirix** [comment]
Logstash documentation [1] says that multiline should be implemented in a Beat plugin rather that in Logstash.  So it seems to be an idiomatic way. It would be nice to see such functionality in a common libbeat and not in concrete beats.

[1] https://www.elastic.co/guide/en/logstash/current/plugins-codecs-multiline.html#_description_153:

> If you are using a Logstash input plugin that supports multiple hosts, such as the Beats input plugin input plugin, you should not use the multiline codec to handle multiline events. Doing so may result in the mixing of streams and corrupted event data. In this situation, you need to handle multiline events before sending the event data to Logstash.

**Comment by towolf** [comment]
My problem is that my software is logging lines longer than 2048 characters. When that happens the lines are split across two messages. 

Really wish there were a way of re-assembling those.


```
"MESSAGE" : "{\"tableName\":\"info_log\", \"log_content\":\"{\"trace\":\"MessageBroker\",\"level\":3,\"ip_address\":\"127.0.0.1\",\"log_content\":\"{\\\"type\\\":\\\"/connection/login\\\", \\\"status\\\":200, \\\"data\\\": {\\\"id\\\" : 94, \\\"notification\\\" : [{\\\"type\\\" : \\\"\\\\/clan\\\\/use_fortress\\\", \\\"from_id\\\" : 0, \\\"send_date\\\" : \\\"2017-07-24 14:39:05\\\", \\\"data\\\" : {\\\"id\\\" : 1, \\\"match_id\\\" : 13, \\\"enemy_clan\\\" : {\\\"id\\\" : 2, \\\"name\\\" : \\\"...\\\", \\\"emblem_info\\\" : {\\\"id\\\" : 2, \\\"layer_objects\\\" : [{\\\"id\\\" : 13, \\\"layer\\\" : 1, \\\"param\\\" : [7, 255, 255, 0, 255, 16, 16, 16, 255, 0, 0, 4096, 4096, 0, 0]}]}}, \\\"fortress\\\" : {\\\"id\\\" : 8, \\\"state\\\" : 10}, \\\"room_id\\\" : 3, \\\"reserve_number\\\" : 30}}, {\\\"type\\\" : \\\"\\\\/clan\\\\/use_fortress\\\", \\\"from_id\\\" : 0, \\\"send_date\\\" : \\\"2017-07-24 14:42:06\\\", \\\"data\\\" : {\\\"id\\\" : 1, \\\"match_id\\\" : 14, \\\"enemy_clan\\\" : {\\\"id\\\" : 2, \\\"name\\\" : \\\"QAStuff\\\", \\\"emblem_info\\\" : {\\\"id\\\" : 2, \\\"layer_objects\\\" : [{\\\"id\\\" : 13, \\\"layer\\\" : 1, \\\"param\\\" : [7, 255, 255, 0, 255, 16, 16, 16, 255, 0, 0, 4096, 4096, 0, 0]}]}}, \\\"fortress\\\" : {\\\"id\\\" : 8, \\\"state\\\" : 10}, \\\"room_id\\\" : 3, \\\"reserve_number\\\" : 31}}, {\\\"type\\\" : \\\"\\\\/clan\\\\/report_defense_win\\\", \\\"from_id\\\" : 0, \\\"send_date\\\" : \\\"2017-07-24 14:42:52\\\", \\\"data\\\" : {\\\"fortress\\\" : {\\\"id\\\" : 8, \\\"state\\\" : 10}, \\\"no_match\\\" : 1, \\\"victory_count\\\" : 0, \\\"id\\\" : 1, \\\"enemy_clan\\\" : {\\\"id\\\" : 2, \\\"name\\\" : \\\"QAStuff\\\", \\\"emblem_info\\\" : {\\\"id\\\" : 2, \\\"layer_objects\\\" : [{\\\"id\\\" : 13, \\\"layer\\\" : 1, \\\"param\\\" : [7, 255, 255, 0, 255, 16, 16, 16, 255, 0, 0, 4096, 4096, 0, 0]}]}}}}, {\\\"type\\\" : \\\"\\\\/clan\\\\/leave\\\", \\\"from_id\\\" : 0, \\\"send_date\\\" : \\\"2017-07-24 14:38:05\\\", \\\"data\\\" : {\\\"id\\\" : 1, \\\"player\\\" : {\\\"id\\\" : 25, \\\"name\\\" : \\\"...\\\"}}}, {\\\"type\\\" : \\\"\\\\/clan\\\\/join\\\", \\\"from_id\\\" : 0, \\\"send_date\\\" : \\\"2017-07-24 14:38:40\\\", \\\"data\\\" : {\\\"id\\\" : 2, \\\"player\\\" : {\\\"id\\\" : 25, \\\"name\\\" : \\\"Styxo\\\"}}}, {\\\"type\\\" : \\\"\\\\/clan\\\\/report_defense_win\\\", \\\"from_id\\\" : 0, \\\"send_date\\\" : \\\"2017-07-24 14:39:43\\\", \\\"data\\\" : {\\\"fortress\\\" : {\\\"id\\\" : 8, \\\"state\\\" : 10}, \\\"no_match\\\" : 1, \\\"victo"
```
cont'd
```
"MESSAGE" : "ry_count\\\" : 0, \\\"id\\\" : 1, \\\"enemy_clan\\\" : {\\\"id\\\" : 2, \\\"name\\\" : \\\"QAStuff\\\", \\\"emblem_info\\\" : {\\\"id\\\" : 2, \\\"layer_objects\\\" : [{\\\"id\\\" : 13, \\\"layer\\\" : 1, \\\"param\\\" : [7, 255, 255, 0, 255, 16, 16, 16, 255, 0, 0, 4096, 4096, 0, 0]}]}}}}], \\\"gas_status\\\" : 0, \\\"ip_bonus\\\" : {\\\"status\\\" : 0}}}\",\"record_date\":\"2017-07-25 12:31:13\"}\"}"
```

**Comment by jagregory** [comment]
This is causing us big issues in part because nearly every stack trace or JSON blob we log is multi-line, and without journalbeat combining them it's very difficult to comfortably read our logs.

I know that's not very constructive, but a big +1 to solving this.

**Comment by mheese** [comment]
does everybody agree that the same logic from `filebeat` would work for them?

I have to admit that I am _very_ reluctant on this one - as they are two different journal events. However, I can totally understand the need for it.

This kind of comes back to one of my last comment in #87 . We should support these kind of use-cases, but I think I want to see some more general approach to them, as features like this easily go through the roof. E.g. I'd also like to have a JSON parser directly in beats.

**Comment by towolf** [comment]
I'm not certain the same approach as in filebeat will work. 

From what I have seen the order of the messages in the systemd journal is not always predictable.

Maybe my two split messages will not always show up right next to each other in the correct order.

**Comment by mheese** [comment]
@towolf that's correct. I wasn't saying that we are going to be able to plug this solution right into journalbeat exactly in the same manner as it works in filebeat nor that it is going to be an easy problem to solve :-)

I guess I was not specific enough with my question: "does everybody agree the same/similar  configuration logic for multiline from `filebeat` would work for them?"

**Comment by stongo** [comment]
we already use filebeat in other cases, so +1 on using same configuration

**Comment by brucemartins** [comment]
just to bump this one a bit, i am curious @mheese is there any progress being made on making this a reality ?

**Comment by SpComb** [comment]
> does everybody agree that the same logic from `filebeat` would work for them?

The multiline usecase for journalbeat might be more complicated, requiring something like the [`logstash-filter-multiline stream_identity`](https://github.com/logstash-plugins/logstash-filter-multiline/blob/368affaeb4170f4a463dfbef0af0b6b838ed2e12/lib/logstash/filters/multiline.rb#L94) to combine events for different processes... you cannot assume that all consecutive lines from a given process will be consecutive in the journal, they may get interleaved with other journal events from other processes.

Also, it's not just the `MESSAGE` field: for the Docker [`--log-driver=journald`](https://docs.docker.com/config/containers/logging/journald/), lines >16KB will be split up into multiple journal events, with (iirc) the heading events having `CONTAINER_PARTIAL_MESSAGE=true`.

**Comment by igoratencompass** [comment]
Any news on this? Very interested in this feature.

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
