### ISSUE TITLE
journalbeat with logstash

### ISSUE THREAD

**Issue by salilwagh** [mheese/journalbeat#39]
Hi @mheese 
I am trying to use journalbeat with logstash which eventually pushes to elastic. But I am not able to push any logs to logstash using journal beat. 

Here is my configuration file. One thing to notice is that I have removed console output and just use logstash:
```name: journalbeat
#tags: [ "blue", "red" ]
input:
  # What position in journald to seek to at start up
  # options: cursor, tail, head (defaults to tail)
  seek_position: cursor

  # If seek_position is set to cursor and seeking to cursor fails
  # fall back to this method.  If set to none will it will exit
  # options: tail, head, none (defaults to tail)
  cursor_seek_fallback: tail

  write_cursor_state: true
  cursor_state_file: /tmp/journalbeat-cursor-state
  flush_cursor_secs: 3

  clean_field_names: true
  convert_to_numbers: false
  move_metadata_to_field: journal
  #default_type: journal
output:
 logstash:
    hosts: ["10.3.0.87:5000"]
```

Please let me know if there are any issues with the above config file or if I am missing anything. Thanks!

**Comment by tronicum** [comment]
i was able to send it to a beats port (like 5044) but waiting now for data to show up in kibana. at least, i now get console messages.

**Comment by tronicum** [comment]
yeah that works. just make sure you have something like
```
input {
  beats {
    port => 5044
  }
}
```
in your logstash config. beats plugin is default on 5.x you might need to install it on earlier versions.

**Comment by salilwagh** [comment]
@tronicum We do have the config in our logstash file. The messages don't show up in console because I have muted them. I just wanted to use logstash output which did not work.

**Comment by mheese** [comment]
@salilwagh I am confused. So does it work now? I can't reproduce this problem myself.

**Comment by salilwagh** [comment]
@mheese, no it did not work for me. I am using ELK and I am using journal beat to push to logstash using the above config file. Logstash is not able to get the logs. Is the above config file correct? One thing I forgot to mention is that I am trying to run it inside a docker container.

**Comment by tronicum** [comment]
I am running this also in a dockerized (both client and server) environment. What does logstash/journalbeat log show after your start journalbeat?

**Comment by tronicum** [comment]
By design journalbeat is a beat not a greylog/pure logstash appender.

**Comment by theblazehen** [comment]
@salilwagh Did you uncomment https://github.com/mheese/journalbeat/blob/master/etc/journalbeat.yml#L248 ?

Just hit that issue myself, spent a few hours on that :/

**Comment by techsolo** [comment]
I got the basic config and enabled the logstash output + enabled and filled in the host. The service starts fine but no connection is made to the logstash server. Anything that I'm doing wrong?

**Comment by salilwagh** [comment]
@theblazehen we are just using LOGSTASH_HOST as the env variable right now in the yaml file for journalbeat. Did not uncomment anything. Currently we went with another image for Journalbeat(https://hub.docker.com/r/sebjay/journalbeat/) and that solved our issue. How does your config file look like?
