### ISSUE TITLE
save RPMs from travis builds

### ISSUE THREAD

**Issue by tronicum** [mheese/journalbeat#42]
Are you interested to save the RPMS (debs whatever) from the travis builds? I am pretty new to travis but could try to do PRs for that. I am using your dockerfiles to build rpms for my own usage but it would be nice to have suchs stuff (and maybe put it to github/releases once in a while)

**Comment by tronicum** [comment]
just found the releases page, with binarys (and wrapping an rpm arround that is not a big thing)

**Comment by mheese** [comment]
I think this is a good idea. We should also build RPMs / DEBs for the different repos. Reopen if you are up for it @tronicum ! 👍

**Comment by tronicum** [comment]
Gonna  have a look on it.

**Comment by tronicum** [comment]
.

**Comment by tronicum** [comment]
inital rpm script. will have a look which docker image we use to run the rpmbuild with.

**Comment by tronicum** [comment]
need to add chckonfig/systemd enable scripts.

**Comment by mheese** [comment]
@tronicum is there no template available from the other beats?

**Comment by tronicum** [comment]
There might be another way to create rpms (converting tar->cpio->rpm) but I don't think elastic publishes .spec files. Even with them we need to create the rpm within Travis docker environment. 
There is a packagecloud integration in Github but their free plan only supports 250mb transfer per month (but you could mirror that back to github).

We could also try to let distros build official packages. I am on "Elternzeit" for 4 weeks maybe I find a solution during that time.

**Comment by mheese** [comment]
@tronicum Maybe `fpm` from Jordan Sissel does the trick? (https://github.com/jordansissel/fpm) ... I never really liked the tool, but some of my colleagues are really into it.

Und genieß Deine Elternzeit :) ... Viel Spaß mit dem/der Kleinen!

**Comment by tronicum** [comment]
Maybe we can pull https://github.com/alanfranz/fpm-within-docker images into Travis

**Comment by rbjorklin** [comment]
@tronicum This might be of interest to you: https://github.com/jordansissel/fpm

**Comment by tronicum** [comment]
@rbjorklin thanks. thats what we discussed the 2 comments above ;)

**Comment by tronicum** [comment]
https://twindb.com/building-rpm-on-travis-ci-in-docker-containers/ (guide on fpm+travisci)

**Comment by tronicum** [comment]
travis/rpm seems to be a complicated topic. above guide is without fpm, and they use a chef-omnibus based solution now (wtf, chef-omnibus to create RPMs??).

**Comment by tronicum** [comment]
they also swiched to packagecloud. I discovered if you ask them niceley (https://packagecloud.io/pricing) for a opensource plan. you get 250gb traffic. would you be open to use that service? it would provide a mirror and provides (global) gpg keys for packages, too. that would outsource hosting (but not building) of the RPMs

**Comment by mheese** [comment]
@tronicum sure, we could use something like packagecloud, however, I don't necessarily see the big advantage over putting the RPMs on github releases? can you tell me the benefits over that?

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
