### ISSUE TITLE
Add support for kernel messages

### ISSUE THREAD

**Issue by hanikesn** [mheese/journalbeat#43]
Apparently journalbeat doesn't export kernel messages right now, which can be accessed by `journalctl --dmesg`.

**Comment by mheese** [comment]
I will investigate, it definitely supported that before. Are you running it restricted somehow? (non-root, SELinux, etc.)

**Comment by nicorevin** [comment]
I've checked with versions `0.1.1` and latest `master` build. Both ship all messages from journal including dmesg.

**Comment by mheese** [comment]
I've also had no issues shipping kernel messages lately.

@hanikesn, we need to know more about your setup so that we can narrow down what is causing your issue.

**Comment by stanxing** [comment]
@mheese @nicorevin I have a question about  how to collect kernel log with journalbeat ,In the journalbeat.yml , I only found units:[] options to config input source ,but kernel log didn't have units. So how should I config the journalbeat.yml?

**Comment by mheese** [comment]
@stanxing if you don't use any `units` in your configuration, you'll receive everything from journald. That will definitely also capture kernel messages.

**Comment by stanxing** [comment]
@mheese Thanks for your reply. My requirement is only to collect several services logs and all kernel logs. Can I implement this requirement with journalbeat?

**Comment by ledmonster** [comment]
@mheese I created a PR for this issue. Could you please review it?
