### ISSUE TITLE
SSL connection

### ISSUE THREAD

**Issue by ashilokhvostov** [mheese/journalbeat#44]
Hi guys, can we use ssl connection with `logstash` like:
https://github.com/elastic/beats/blob/master/filebeat/filebeat.yml#L95-L103

**Comment by mheese** [comment]
Theoretically that should work as this functionality is all part of the beats framework. However, it might be necessary for it to update to `elastic/beats` 5.1.x first (which is dealt with in #38).

**Comment by nicorevin** [comment]
@ashilokhvostov you should be able to use ssl with https://github.com/mheese/journalbeat/blob/95c8a3c6683cedc5cd969c9ad91df79aebb973ff/etc/journalbeat.yml#L266

**Comment by rbjorklin** [comment]
Fantastic @nicorevin! Is there a new release in the works or should I build locally while waiting?

**Comment by nicorevin** [comment]
@rbjorklin https://github.com/mheese/journalbeat/releases/tag/v5.1.2

**Comment by mheese** [comment]
@ashilokhvostov looks like we can close this?
