### ISSUE TITLE
Add journalbeat.template.json.

### ISSUE THREAD

**Issue by Rotwang** [mheese/journalbeat#47]
Hi, it seems quite common that beats deliver their own index template:

https://github.com/elastic/beats/blob/master/filebeat/filebeat.template.json
https://github.com/elastic/beats/blob/master/metricbeat/metricbeat.template.json
https://github.com/elastic/beats/blob/master/packetbeat/packetbeat.template.json

Could you provide something similar for journalbeat?

**Comment by strootman** [comment]
I believe that the creation of this beat precedes the following instructions, but generation of index templates is now "baked" into the developer workflow for new beats.

https://www.elastic.co/blog/build-your-own-beat

**Comment by mheese** [comment]
right, as one can directly import to ES, it should come with an index template.

**Comment by mheese** [comment]
if anybody went through that tedious work already... always welcome :)

**Comment by basvandijk** [comment]
I'm setting up a machine with Elasticsearch and Kibana and I would like to use journalbeat to ship the logs of all my machines to this Elasticsearch machine. I'm new to Elasticsearch and I'm wondering if I need this `journalbeat.template.json` file or if I can just set `template.enabled: false`?

Does anybody have an example of a working `journalbeat.template.json` file?

Thanks!

**Comment by basvandijk** [comment]
I now have the following `journalbeat.template-es2x.json` and that seems to work:

```json
{
   "template" : "journalbeat-*",
   "mappings" : {
      "journal" : {
         "properties" : {
            "input_type" : {
               "type" : "string"
            },
            "@timestamp" : {
               "type" : "date",
               "format" : "strict_date_optional_time||epoch_millis"
            },
            "journal" : {
               "properties" : {
                  "code_line" : {
                     "type" : "integer"
                  },
                  "user_id" : {
                     "type" : "string"
                  },
                  "syslog_pid" : {
                     "type" : "integer"
                  },
                  "hostname" : {
                     "type" : "string"
                  },
                  "exe" : {
                     "type" : "string"
                  },
                  "cap_effective" : {
                     "type" : "string"
                  },
                  "comm" : {
                     "type" : "string"
                  },
                  "systemd_user_slice" : {
                     "type" : "string"
                  },
                  "catalog_entry" : {
                     "type" : "string"
                  },
                  "systemd_slice" : {
                     "type" : "string"
                  },
                  "systemd_owner_uid" : {
                     "type" : "string"
                  },
                  "boot_id" : {
                     "type" : "string"
                  },
                  "session_id" : {
                     "type" : "string"
                  },
                  "systemd_invocation_id" : {
                     "type" : "string"
                  },
                  "systemd_cgroup" : {
                     "type" : "string"
                  },
                  "errno" : {
                     "type" : "string"
                  },
                  "invocation_id" : {
                     "type" : "string"
                  },
                  "message_id" : {
                     "type" : "string"
                  },
                  "unit" : {
                     "type" : "string"
                  },
                  "audit_session" : {
                     "type" : "string"
                  },
                  "pid" : {
                     "type" : "integer"
                  },
                  "code_file" : {
                     "type" : "string"
                  },
                  "result" : {
                     "type" : "string"
                  },
                  "systemd_unit" : {
                     "type" : "string"
                  },
                  "transport" : {
                     "type" : "string"
                  },
                  "exit_code" : {
                     "type" : "integer"
                  },
                  "cmdline" : {
                     "type" : "string"
                  },
                  "audit_loginuid" : {
                     "type" : "integer"
                  },
                  "exit_status" : {
                     "type" : "string"
                  },
                  "uid" : {
                     "type" : "integer"
                  },
                  "machine_id" : {
                     "type" : "string"
                  },
                  "systemd_session" : {
                     "type" : "string"
                  },
                  "gid" : {
                     "type" : "integer"
                  },
                  "syslog_identifier" : {
                     "type" : "string"
                  },
                  "code_function" : {
                     "type" : "string"
                  },
                  "priority" : {
                     "type" : "short"
                  },
                  "syslog_facility" : {
                     "type" : "integer"
                  },
                  "source_realtime_timestamp" : {
                     "type" : "lonmg"
                  },
                  "source_monotonic_timestamp" : {
                     "type" : "string"
                  },
                  "leader" : {
                     "type" : "string"
                  },
                  "executable" : {
                     "type" : "string"
                  }
               }
            },
            "type" : {
               "type" : "string"
            },
            "beat" : {
               "properties" : {
                  "name" : {
                     "type" : "string"
                  },
                  "version" : {
                     "type" : "string"
                  },
                  "hostname" : {
                     "type" : "string"
                  }
               }
            },
            "message" : {
               "type" : "string"
            }
         }
      }
   }
}
```

**Comment by nicorevin** [comment]
@basvandijk I think the reason why there is still no template here is that the set of non-movable fields is the same as for any other beat. And everything else can be done depending on your `clean_field_names` and `move_metadata_to_field` configuration settings (and depending on what you will filter out from the journal entry).

**Comment by basvandijk** [comment]
@nicorevin I see but it would at least be nice to have an example to start from. 

(Note that I added a bunch of `"index": "not_analyzed"` to my `journalbeat.template-es2x.json`).

**Comment by mheese** [comment]
@basvandijk I like your example. Do you want to create a PR for this? With the obvious note that there need to be those 2 configuration values set.

@nicorevin and yes, because of the flexibility of configuration of this beat, I was reluctant to create an index template for this from the start. Nonetheless I think it would be a good idea (and even if it is just for documentation purposes) to have some examples around to help people to get started.

**Comment by basvandijk** [comment]
@mheese yes I'll create a PR for this. However I'm currently in the process of upgrading my elasticsearch-2.4.4 to 5.4 and I'm noticing some types like `string` are deprecated in favor of `text` or `keyword`. When I finish the upgrade (I'm currently having some problems with kibana timing out on elasticsearch) I'll update the template and make a PR.

**Comment by CtrlC-Root** [comment]
In case it helps anyone else, here are index templates for 2.X and 5.X with `clean_field_names: true` and without `move_metadata_to_field`:

* https://github.com/CtrlC-Root/pkg-journalbeat/blob/master/journalbeat.template-es2x.json
* https://github.com/CtrlC-Root/pkg-journalbeat/blob/master/journalbeat.template.json

**Comment by a3linux** [comment]
how about anyone help to generate a journalbeat.templte-es6x.json here?

**Comment by CtrlC-Root** [comment]
The templates I posted above are still missing a few fields I've seen recently in Kibana (i.e. `audit_*`). I assume most of these are determined by `journald` and not `journalbeat`. Does anyone know if there's a place that lists all of them so I can add them to my templates?

@a3linux why don't you do it and post it here for others to use?

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
