### ISSUE TITLE
program ignores ctrl+c

### ISSUE THREAD

**Issue by dwerder** [mheese/journalbeat#5]
The program seems to ignore SIGNAL TERM. If you start it with output console. You can only stop the program with `kill -9`. A normal TERM is ignored.

System:
```
CentOS Linux release 7.2.1511 (Core)
Linux Host 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mheese** [comment]
Did you also compile this with go 1.6.x I assume? With my last compile, I cannot reproduce this. There might be some channel keeping things open for some reasons. If this persists, I will add some special signal handling (what we probably should do anyway).

**Comment by dwerder** [comment]
Yes, we use go version go1.6.1 linux/amd64

**Comment by kinghrothgar** [comment]
I have compiled with go1.5.3 and am also having this problem.  It stops tailing logs but does not exit when you send it a SIGTERM.  I am also on CentOS 7

**Comment by mheese** [comment]
thanks to @kinghrothgar for the easy fix

**Comment by kinghrothgar** [comment]
There are still some edge cases that cause this still to happen.  I should hopefully get around to pull requesting a fix next week.

**Comment by nh2** [comment]
@kinghrothgar This still happens to me; when I `kill $(pidof journalbeat)`, it happily ignores the sigterm and continues running (I can see it in strace). It gets to line https://github.com/mheese/journalbeat/blob/f0a328caa5af485c3f0f34d3853b5bfd313b35b6/beater/journalbeat.go#L241 but doesn't terminate.

**Comment by mimmus** [comment]
Same for me.
"Stopping Journalbeat" is printed but journalbeat continues running, another CTRL-C kills it (but cursor state is not saved).
