### ISSUE TITLE
Create docker hub image for mheese/journalbeat

### ISSUE THREAD

**Issue by mbrooks** [mheese/journalbeat#53]
Now that we have a docker image, it would be nice if the image was available in docker hub. Please setup docker hub and use the namespace 'mheese' for the docker image. 

The docker hub image should include instructions on the following:
* quickstart of journalbeat using the LOGSTASH_HOST env var
* how to easily mount in your own custom journalbeat configuration file to override the default config
* how to extend from this docker image and build your own: either integrate your own config file, do fancy service discovery

**Comment by mheese** [comment]
@mbrooks please provide me your dockerhub account name and I will add you as an admin on the repo! (I added you as collaborator on the github repo already)

**Comment by mbrooks** [comment]
@mheese I believe it's `aubiematt`.

**Comment by mheese** [comment]
@mbrooks added you as a collaborator on the repo

**Comment by mbrooks** [comment]
@mheese I don't see the project in docker hub. Can you check that you added `aubiematt` and not `mbrooks`. Someone has my github name over there.

**Comment by mheese** [comment]
@mbrooks I added `aubiematt` as a collaborator ... here is the link: https://hub.docker.com/r/mheese/journalbeat/

there is no image pushed yet .... but you should be able to do that now

**Comment by mbrooks** [comment]
The docker image is live! I have an example of what a tagged image will look like, but we haven't created a tag in a while, so it's got a version count on it.

Check it out:
https://hub.docker.com/r/mheese/journalbeat/tags/

**Comment by mbrooks** [comment]
We're still lacking a document for Docker Hub. I'll try to write that tonight or tomorrow for inclusion into docker hub.

**Comment by mbrooks** [comment]
Docker documentation has been updated in `docker/README.md`. To update the description on docker hub, I would copy and paste the `How to use this image` section and include any other Journalbeat specific information that may want to be included  into the docker hub description on the docker hub website. Since I do not have access to update the description, I will need someone with access to do this.

**Comment by mbrooks** [comment]
I realized that I have no clue how to associate a PR with an issue, so here it is:
https://github.com/mheese/journalbeat/pull/57
