### ISSUE TITLE
Identify what would need to be done to become a kubernetes log shipper

### ISSUE THREAD

**Issue by mbrooks** [mheese/journalbeat#54]
Now that we have a docker image, it would be nice if we could build an image that we can plug in as a kubernetes log shipper. The end goal would be a log shipper that lets people run journalbeats docker image instead of the default fluentd daemon sets. This issue is to identify all the things that need to be done to make this a reality so that we can create issues and start working on various pieces.

**Comment by mbrooks** [comment]
@mheese @nicorevin Please tag anyone you know maybe able to contribute towards this discussion.

**Comment by dbason** [comment]
I think the major biggest requirement will be translating kubernetes metadata (e.g. pod-name etc).  It looks like this is going to be a built in processor for filebeat as of 6.0.0 for the json-file driver.

I think one of the benefits of fluentd is that it can switch between journald and json-file based on an environment variable passed in.  If you wanted to have that for a beats product you'd need to package both journalbeat and filebeat in an image and then select between them with a wrapper script.

**Comment by SleepyBrett** [comment]
@dbason we're just attempting to run two pods per node, we already have filebeat dealing with all the pod logs, soon also the audit log. Journalbeat will run along side picking up the journal logs from the node. I'd rather have two small footprint specialized log shippers than the swiss army knife (and memory hog) that fluentd is.

**Comment by nicorevin** [comment]
@SleepyBrett don't intend to upset you but systemd is a CPU hog. See https://github.com/systemd/systemd/issues/5102
While it is ok for system-level logging (which is usually low-volume) when it comes to a "noisy" application wrapped in docker with `--log-driver=journald` this will distress anyone.

Docker starting from 17.06 supports [logging plugins](https://docs.docker.com/engine/extend/plugins_logging/) but I don't know if anyone looked into them yet. Implementing a beats plugin for docker would help significantly and allow to avoid using tools like fluentd. 

See also https://kubernetes.io/docs/concepts/cluster-administration/logging/

**Comment by theRealWardo** [comment]
we're trying to get to the point that we can run one log shipping daemon per host. right now I'm configuring the docker daemon to use `--log-driver=journald` and then I have some code which effectively does a `docker inspect` to load additional metadata and attach it to the log entry that is pushed to elasticsearch. the code is currently sitting in my little fork over at https://github.com/theRealWardo/journalbeat but it needed a new dependency and I wasn't very comfortable with that so I migrated to dep hence the above PR first. I'd love to contribute back what works well for us if the authors are welcome to it!

**Comment by SleepyBrett** [comment]
@nicorevin we are, in fact, just shipping low volume system logs with journalbeat.. well system level and the kubelet (which we run as a rkt pod).

**Comment by mheese** [comment]
@nicorevin let's also not forget that these are recognized bugs and are actively worked on (or merged already e.g.) ... it's just the normal performance improvement cycle that new software like systemd/journald needs to undergo as well

The "beauty" or advantage of using journald for docker logs as well is that you can run journald in a non-persistent mode on servers which can satisfy some strong compliance regulations.

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
