### ISSUE TITLE
CloudNativeCon + KubeCon Berlin 2017

### ISSUE THREAD

**Issue by mheese** [mheese/journalbeat#59]
Hey everybody,

I'm using this issue tracker to send out a notice that I'm going to attend the KubeCon in Berlin next week. It would be lovely to meet anybody who is interested in `journalbeat` or has opinions about `journalbeat` or is just using `journalbeat`.

My rough schedule for the 3 days is here: https://cloudnativeeu2017.sched.com/marcus.heese . I'm definitely trying to attend the Elastic talk (https://cloudnativeeu2017.sched.com/event/9Tcd/360deg-monitoring-of-your-services-i-philipp-krenn-elastic) which would be an appropriate place to talk about `journalbeat` afterwards.

@nicorevin, @mbrooks, @kinghrothgar, it would be especially nice to get to know any of you guys in person if you attend!

Cheers
Marcus

**Comment by mbrooks** [comment]
Unfortunately, I can't make it to Berlin this time. Maybe I can join virtually if any of you plan to meet up on Google Hangouts or something!
