### ISSUE TITLE
tail mode not tailing?

### ISSUE THREAD

**Issue by jkrauska** [mheese/journalbeat#60]
I would expect 
  seek_position: head
to grab only NEW journal log lines as they happen.

Occasionally I want to dump the backlog and just start logging fresh.

Something like the -f option in journalctl.

However, journalbeat appears to be shipping all of my log history in journalctl.

I am running an older version of journalctl, so I can't easily use the --vacuum option to delete old logs.

Can you take a look at the code and check about tail mode?

Am I misinterpreting how tail is expected to work?

Does tail mean 'oldest' or 'newest'?

log output:

2017/03/31 20:27:09.685509 logstash.go:90: INFO Max Retries set to: 3
2017/03/31 20:27:09.685608 outputs.go:106: INFO Activated logstash as output plugin.
2017/03/31 20:27:09.685704 publish.go:291: INFO Publisher name: journalbeat
2017/03/31 20:27:09.686053 async.go:63: INFO Flush Interval set to: 1s
2017/03/31 20:27:09.686066 async.go:64: INFO Max Bulk Size set to: 2048
2017/03/31 20:27:09.688212 journalbeat.go:50: INFO Seek to tail successful
2017/03/31 20:27:09.688291 beat.go:207: INFO journalbeat start running.
2017/03/31 20:27:09.688304 journalbeat.go:129: INFO Journalbeat is running!
2017/03/31 20:27:09.688523 state.go:119: WARN could not read the pending queue: open .journalbeat-pending-queue: no such file or directory
2017/03/31 20:27:09.688533 state.go:121: INFO Loaded 0 events, trying to publish

yaml:
journalbeat:
  seek_position: tail
  cursor_seek_fallback: tail
  cursor_flush_period: 5s
  clean_field_names: true
  convert_to_numbers: false
  move_metadata_to_field: journal
  write_cursor_state: false

name: journalbeat

output.logstash:
  enabled: true
  hosts: ["${LOGSTASH_HOST}"]

logging.to_files: false

**Comment by mheese** [comment]
I guess it's always depending on your point of view what is the `head` and what is the `tail` 😄 .

The idea is that `tail` works the same as a unix `tail -f` - *only* grabbing *new* logs after startup.
`head` will always grab **everything** that is still available in your journald. This option is probably only useful if you are extremely paranoid about losing logs, and still then, `cursor` is probably the best option. It will write the state of the current position to disk, and tries to continue from there if the program gets restarted - aiming at not reading/sending logs twice, but also not losing any (as `tail` will probably do).

I would personally recommend `cursor`, but depending on your setup and needs, the other options are available as well.

@jkrauska does that answer your question? Also, does it now behave as expected? Because if not, we might have a potential bug - although I could not reproduce it right now ... which does not mean that it is not a bug :)

**Comment by jkrauska** [comment]
Right  -- In 'tail' mode I repeated was seeing the entire journal history being sent, which is what I would expect for 'head'.

I will attempt to reproduce in a simpler environment where I can blow away indexes and see what happens when I restart journalbeat.

--Joel

**Comment by mheese** [comment]
@jkrauska, ok sorry ... I think I misunderstood you.

Can you tell me more about your setup? Which distro, systemd version, journalbeat version, etc.

**Comment by jkrauska** [comment]
@mheese no worries...

distro: debian 8.x
systemd: 215-17+deb8u6
journalbeat version 5.2.1 (amd64), libbeat 5.2.1

FWIW: I want to avoid cursor as I have daemons that occasionally spew huge amounts of logs that get backlogged and I want to skip/ignore -- thus tail.

**Comment by mheese** [comment]
@jkrauska I'm following up the code paths here and trying to figure out what could go wrong ... as your log states that the seek was successful, I'm not sure what could have gone wrong on our end.

The calls pretty much translate directly to C to the seek function calls as described here: https://www.freedesktop.org/software/systemd/man/sd_journal_seek_head.html

It's maybe also worth following up if there is a bug related to your systemd version? Can you reproduce the behaviour with another tool?

Also, please provide your `journald.conf` (if you can / are allowed to https://www.freedesktop.org/software/systemd/man/journald.conf.html) ... that might provide some more insight as well.

If this all does end up nowhere, I'll try to reproduce it with a VM ... Thanks for the help :)

**Comment by arypurnomoz** [comment]
i also got this problem and `cursor_state_file` wasn't created even when `write_cursor_state: true` and `seek_position`

Journalbeat 0.1.1  was alright thou

**Comment by mheese** [comment]
@arypurnomoz @jkrauska thanks guys, I think I've got a suspicion what is going wrong here ... we changed the go systemd library from my fork to the main one from coreos, there must be something going wrong now

@arypurnomoz what are your system versions? OS, systemd, journalbeat, etc.

**Comment by jkrauska** [comment]
Are you able to reproduce?

I've been considering firing up some simple VMs, but if you already have a scenario where you can reproduce, I'll stand down.

**Comment by arypurnomoz** [comment]
debian 8.7, systemd 215, journalbeat (latest journalbeat release) version 5.1.1 (amd64), libbeat 5.1.1

config:
```yaml
name: journalbeat
journalbeat:
  seek_position: cursor
  cursor_seek_fallback: tail

  write_cursor_state: true
  cursor_state_file: /var/lib/filebeat/journalbeat-cursor-state
  cursor_flush_period: 2s

  clean_field_names: true
  convert_to_numbers: true
  default_type: journal
      
output.elasticsearch:
  hosts: ["localhost:9200"]
  index: "logs"
  pipeline: journald
  template.enabled: false
    
logging.level: info
```

**Comment by jkrauska** [comment]
@mheese any news here?

**Comment by nicorevin** [comment]
@arypurnomoz @jkrauska I've just checked my setup using `seek_position: tail` and it is working properly as expected. Tested with the latest stable debian and systemd 215. 
journalbeat v 5.2.1 built from source in debian 8.7

**Comment by jkrauska** [comment]
I was using the container version -- @nicorevin do you have a container build?

**Comment by nicorevin** [comment]
I believe I also tested it using a docker container.

**Comment by yyyyyyyyyg** [comment]
@jkrauska did you fix your issue? I am using the container version 5.6.8 with the "seek_position: cursor  cursor_seek_fallback: tail", but still grabbing the old journal logs.

**Comment by wklken** [comment]
hi guys, any update? I met the same issue, I built the binary in docker with centos:7

**Comment by wklken** [comment]
If found that, after calling `jb.journal.SeekTail`, 

```
err = seekToHelper(config.SeekPositionTail, jb.journal.SeekTail())

# here got %!s(uint64=1)
o, err := jb.journal.Next()
```

**Comment by edgar1992** [comment]
I also met the issue on centos7.3 and ubuntu 16.04，Is there any solution to this problem?

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
