### ISSUE TITLE
RFE - Add Dockerfile labels for RHEL "atomic install"

### ISSUE THREAD

**Issue by lcarstensen** [mheese/journalbeat#61]
journalbeat is a system-level container suitable for log-shipping from any Fedora / CentOS / RHEL / RHEL Atomic host in an  ELK-using shop.  Red Hat is following a set of Docker labels they've published for docker-run install/uninstall/run arguments that would simplify things further for admins to just "atomic install journalbeat".  You might consider adding/maintaining some of those labels to journalbeat's dockerfile (or I could submit a PR):

https://github.com/projectatomic/ContainerApplicationGenericLabels
https://developers.redhat.com/blog/2015/04/21/introducing-the-atomic-command/

**Comment by mheese** [comment]
@lcarstensen very good point. As I've worked with Atomic before, I still remember that I aimed for having all these labels in our system-level docker images. They were not that sophisticated though at that time.

IMHO, they do not hurt, so we definitely should do that as it will massively improve the experience on Atomic based hosts.

@mbrooks, @nicorevin, is there anything similar for CoreOS available that we should do?

@lcarstensen, if you want to implement that feature, please feel free to work on it and create a PR. I'll assign this to you  then.

**Comment by mbrooks** [comment]
I need to do a bit of research here before I can comment, as I am unfamiliar with atomic and CoreOS.

What I do know is that our Docker build process doesn't really fit in to what a standard docker build process should look like. This is because we're having to build the binary first in docker, and then building a second docker container for what we want to distribute. I wonder if this will affect how atomic works as well, but I don't know.

**Comment by qubusp** [comment]
I don't get it though - is this working with CentOS or no?

**Comment by lcarstensen** [comment]
@mheese - I've been distracted elsewhere, but intended to work up a PR when I am working back near journalbeat again.

@mbrooks - journalbeat's docker build process will be fine regardless of what it is as at the end of the day we're just adding some extra labels to the final docker image.  That could even be done as one extra image layer at the end, although I'd prefer not.

@qubusp - atomic is available in Fedora, CentOS, and RHEL and provides package-manager-like installation of docker images into the init system / systemd.  I haven't provided a pull request though, yet.  The question above was directed towards CoreOS experts asking what CoreOS has similar to atomic in Fedora/CentOS/RHEL.

**Comment by nrvnrvn** [comment]
Please consider migrating to the official Elastic Journalbeat
https://www.elastic.co/guide/en/beats/journalbeat/current/index.html
