### ISSUE TITLE
Writing the cursor state file is not atomic

### ISSUE THREAD

**Issue by olasd** [mheese/journalbeat#64]
Hey,

I'm deploying journalbeat to my infrastructure, and I added a nagios check[1] to compare the journalbeat cursor state and the current systemd journal cursor.

[1] https://forge.softwareheritage.org/diffusion/SPPROF/browse/master/files/icinga2/plugins/check_journal

Unfortunately, sometimes, the check fails because the cursor state file is empty, which sounds like a race condition between updating the file and reading it.

I think making writes to the file atomic would be a good idea anyway, as if journalbeat crashes during the file write for whatever reason, it wouldn't know from where to restart.

Thanks!

**Comment by nicorevin** [comment]
Hey, 

This is a good point.
The cursor file is empty sometimes because https://golang.org/pkg/io/ioutil/#WriteFile used to flush data to the file truncates it before writing. There is a chance that we will lose the cursor in this case.

The same can be applied to the pending queue as well.

**Comment by nicorevin** [comment]
ran into ```ERR error writing .journalbeat-pending-queue: rename /tmp/journalbeat-pending-queue091154199 .journalbeat-pending-queue: invalid cross-device link``` issue. 
will change the way tempfiles are handled.
