### ISSUE TITLE
Implement filebeat-style json processing

### ISSUE THREAD

**Issue by heyimalex** [mheese/journalbeat#69]
This is more a question of whether a pull request would be accepted than an actual issue. I think it's pretty common these days to log events in json format to stdout, and filebeat has the ability to parse and process these lines as json before shipping them off. Unfortunately, using filebeat with systemd is not very straightforward because systemd won't log to a file. You can either manage logging within the app itself or go through syslog. Both are pretty suboptimal.

I'm thinking that implementing the same json processing functionality into journalbeat itself will make life easier. I'm not very familiar with either codebase, but I imagine ripping json parsing logic out of filebeat won't be too awful. Give me the green light and I'll give it a shot!

**Comment by nicorevin** [comment]
This has already been implemented for us! :)

So you can easily drop something like [this](https://www.elastic.co/guide/en/beats/filebeat/current/decode-json-fields.html) into your [config file](https://github.com/mheese/journalbeat/blob/master/etc/journalbeat.yml#L91).

**Comment by heyimalex** [comment]
No way? That's awesome! I remember doing some research a while ago to see if it was possible, but I'm glad I was wrong 😅
