### ISSUE TITLE
Install not working.

### ISSUE THREAD

**Issue by ahmebane** [mheese/journalbeat#76]
go get github.com/mheese/journalbeat
package context: unrecognized import path "context" (import path does not begin with hostname)

Other co get commands Ive tried work, such as the 'hello' example.

**Comment by nicorevin** [comment]
Hello @ahmebane!

It would be good to know the environment you are executing this command.

```bash
$ docker run --rm -ti golang bash

root@a46d83d9ced9:/go# go version
go version go1.8.3 linux/amd64

root@a46d83d9ced9:/go# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

root@a46d83d9ced9:/go# apt-get update
<...>

root@a46d83d9ced9:/go# apt-get install libsystemd-dev
<...>
Setting up libsystemd-dev:amd64 (215-17+deb8u7) ...

root@a46d83d9ced9:/go# go get github.com/mheese/journalbeat

root@a46d83d9ced9:/go# which journalbeat
/go/bin/journalbeat

root@a46d83d9ced9:/go# journalbeat --version
journalbeat version 5.4.1 (amd64), libbeat 5.4.1
```

As far as I know all the [release binaries](https://github.com/mheese/journalbeat/releases) are distribution agnostic (although built against different distributions) self-sufficient binaries and could be used in whatever linux distribution you want.

I would try them first. In this case you won't need golang and libsystemd-dev as dependencies.

**Comment by ahmebane** [comment]
I'm running on Ubuntu 16.04 LTS. Did something about the install process change in the last month or so? I was successful in early May, but I don't think I was using the 'go get' process.

My go version is 1.6.2 - I just installed it today:
 
ubuntu@ip-172-31-22-222:~$ go version
go version go1.6.2 linux/amd64

I'm not so worried about the binary - i'm more concerned with making sure everything is set up for journalbeat to run as a service - not sure what all has to be touched. 

Thank you.

**Comment by ahmebane** [comment]
dang - didn't mean to close it!

**Comment by nicorevin** [comment]
I don't think go 1.6.2 is supported by elastic beats. 
package context was moved to standard library in Go 1.7.
See https://golang.org/doc/go1.7#context and 
https://www.elastic.co/guide/en/beats/devguide/current/beats-contributing.html#setting-up-dev-environment.

Everything you need to run is a single binary. That's why I recommend using any available from the releases page.

**Comment by ahmebane** [comment]
OK, moving to 1.8 fixed the go get - thanks. However, it didn't really do an install - it just pulled the code. When I last installed journalbeat, it put the binary in /bin/, created the /etc/journalbeat directory, etc. I have not used go  - sorry for the newb questions. Do I need to run something after the go get to get the install completed? Thanks again!

**Comment by nicorevin** [comment]
When you run `go get smth` it will put that `smth` to the `$GOPATH/bin` path.
To be able to run `journalbeat` please ensure that this path is part of the `$PATH`.
I would still recommend not to hassle with it and download the binary from the releases page and put it to `/usr/local/bin` or whatever.
Then you need to get the https://github.com/mheese/journalbeat/blob/master/etc/journalbeat.yml and tune it for your needs.
Then run `journalbeat -c $PATH_TO_YOUR_journalbeat.yml`

I think the `Install` section of the readme is misleading. It is outdated and was written back then when there were no binary releases. Sorry about that.
