### ISSUE TITLE
Official image (on dockerhub) lags behind releases

### ISSUE THREAD

**Issue by SleepyBrett** [mheese/journalbeat#83]
The last release on dockerhub is 5.1.2 (4 months old).

**Comment by nicorevin** [comment]
@mheese I believe only you can make the necessary changes to the `.travis.yml` so that it could push the images to the docker hub.

**Comment by mheese** [comment]
@nicorevin I'm currently reluctant to integrate that with Travis. It would require another docker hub "robot" account, etc. For now we just need to build/push also on release unless somebody comes up with a better idea. I know that `quay.io` might be a better choice actually.

@mbrooks, opinions are welcome :)

Closing this, as I just brought it up to speed.

**Comment by mbrooks** [comment]
@mheese Right now our process isn't automated, so we need to remember to run `make docker-push` when there is a new tag released. I can do this, if we haven't done it. Travis is capable of doing this, if we want it to do it, but we may need to tweak the make scripts to only push if it is a tag.
