### ISSUE TITLE
units option does not work

### ISSUE THREAD

**Issue by hookenz** [mheese/journalbeat#89]
It seems that units need to be prefixed with "_SYSTEMD_UNIT=" for each entry.
But for me, that didn't solve it either.

Any ideas?

**Comment by nicorevin** [comment]
I think you need not.
https://github.com/mheese/journalbeat/blob/master/beater/journalbeat.go#L87
https://github.com/coreos/go-systemd/blob/master/sdjournal/journal.go#L341
https://github.com/coreos/go-systemd/blob/abf023b1f0f04b4cd92e02b21c5406ab18a85f08/sdjournal/journal.go#L444
https://www.freedesktop.org/software/systemd/man/sd_journal_add_match.html#Examples
https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#_SYSTEMD_CGROUP=

**Comment by hookenz** [comment]
Ok, now it's working.  However, I think _SYSTEMD_UNIT is possibly a little naive.  It misses some events related to the service.  Looking at the `journalctl -u` code it applies a filter with the following:

#define SYSTEM_UNITS                 \
        "_SYSTEMD_UNIT\0"            \
        "COREDUMP_UNIT\0"            \
        "UNIT\0"                     \
        "OBJECT_SYSTEMD_UNIT\0"      \
        "_SYSTEMD_SLICE\0"
