### ISSUE TITLE
Should units filter work like journalctl -u?

### ISSUE THREAD

**Issue by hookenz** [mheese/journalbeat#90]
Journalctl -u filters much more than just _SYSTEMD_UNIT.  But also, other related events such as crashdumps which come out under COREDUMP_UNIT.  That's an important piece of information.

As such, the following would more closely match what it does.  Also of note, in the original code should there have been a  call to `jb.journal.AddDisjunction()` at the end of the original loop?  I am unsure how it behaves without it when multiple units array entries are input.

````
// add specific units to monitor if any
for _, unit := range jb.config.Units {
    // Look for messages from the service itself
    if err = jb.journal.AddMatch("_SYSTEMD_UNIT=" + unit); err != nil {
        return fmt.Errorf("Filtering unit %s failed: %v", unit, err)
    }

    // Look for coredumps of the service
    jb.journal.AddDisjunction()
    jb.journal.AddMatch("MESSAGE_ID=fc2e22bc6ee647b6b90729ab34a250b1")
    jb.journal.AddMatch("_UID=0")
    jb.journal.AddMatch("COREDUMP_UNIT=" + unit)

    // Look for messages from PID 1 about this service
    jb.journal.AddDisjunction()
    jb.journal.AddMatch("_PID=1")
    jb.journal.AddMatch("UNIT=" + unit)

    // Look for messages from authorized daemons about this service
    jb.journal.AddDisjunction()
    jb.journal.AddMatch("_UID=0")
    jb.journal.AddMatch("OBJECT_SYSTEMD_UNIT=" + unit)

    // Show all messages belonging to a slice
    if strings.HasSuffix(unit, ".slice") {
	jb.journal.AddDisjunction()
	jb.journal.AddMatch("_SYSTEMD_SLICE=" + unit)
    }

    jb.journal.AddDisjunction()
}
````

If the above makes sense, then I'll tidy it up and create a pull request for it.

**Comment by mheese** [comment]
Not having looked at this in detail, I'd say "probably yes" :) 

The behaviour should not deviate from `journalctl -u`. I actually would probably consider this as a bug from a user point of view.

**Comment by hookenz** [comment]
Ok, working on a cleaner solution.  I'll put in a pull request shortly.

**Comment by hookenz** [comment]
Pull request done.   https://github.com/mheese/journalbeat/pull/91

**Comment by hookenz** [comment]
Sorry for the delay @mheese.  I have it pretty much done and I'm now testing it.  It took a while to figure out how the journalctl filter code actually works.  It's not well documented.  The upshot is units can now be expressed in journalbeat.yml as:

     units = [ "unitname", "unitname.service", "unit*", "unitname.*", "unitname@[1-5].*" ] // etc.

**Comment by hookenz** [comment]
Any update on the PR I did fir this?

**Comment by nicorevin** [comment]
merged!

**Comment by mheese** [comment]
thanks guys ... I'm currently fighting with an injury (and trying to keep up with boat loads of work) - I apologize if I'm not the fastest to respond currently
