### ISSUE TITLE
Investigate building a universal linux binary

### ISSUE THREAD

**Issue by nicorevin** [mheese/journalbeat#92]
My personal tests show that there is no need for building a binary across different distributions. You can use a binary built in centos with systemd 215 (for instance) and run it in the latest archlinux/debian/CoreOS.

I haven't yet seen any unexpected implications and drawbacks.

Would be great to know if anyone is as happy as me with this approach.

**Comment by hookenz** [comment]
That won't work distros that don't the usual gcc std lib installed.  Thanks to the cgo dependency
e.g. Alpine.   Docker solves all those dependency issues quite nicely.  Some people don't like it of course.

**Comment by nicorevin** [comment]
Alpine is a different beast. I don't even take it into account here since we're tied to systemd libraries. 
The question is that now we build releases for different distros. And it seems to not make any sense to do it. 
You can build journalbeat using ubuntu and re-use the resulting binary anywhere with systemd thanks to https://lists.freedesktop.org/archives/systemd-devel/2016-November/037836.html

**Comment by hookenz** [comment]
It'd be possible provided the C library doesn't change.  There is no guarantee that won't happen.  I had an issue 2 years ago with a binary built on Ubuntu 10.04 that wouldn't run on 14.04 or similar.  It was because the C runtime was updated.  I had to rebuild even though there was no real change.  And then there is Centos.  Super old, super conservative with updates.   You'd have to test it.

**Comment by hookenz** [comment]
@nicorevin -  The journal format is documented apparently.  We could open it and read it directly thereby removing the cgo dependancy.  It's tempting to do but there are other features is like in journalbeat first...   I wish there were more hours in the day.

**Comment by nicorevin** [comment]
The Journal has got only C API to read the journal with. This is why go-systemd needs systemd headers and dynamically lunks to ststemd libraries

**Comment by nicorevin** [comment]
So I've tested running the latest release binaries (centos, debian and fedora) and the one we build ourselves on the same CoreOS host. All four predictably run stable, have no issues and ship all logs to the output.

Since I develop under macos I just put [these headers](https://github.com/systemd/systemd/tree/master/src/systemd) into `vendor/github.com/coreos/go-systemd/sdjournal/systemd` to make a build.
All the real job is done via dynamically linking the systemd library.
There is no difference in this either.
I've tried:
```sh
$ sudo ./journalbeat-<flavour> -c /etc/journalbeat.yml -e
# and in separate tty
$ ps aux | \
  grep "\./journalbeat" | \
  grep -v sudo | \
  grep -v grep | \
  awk '{print $2}' | \
  xargs -I{} sudo lsof -p {} | \
  grep "\.so" | \
  awk '{print $9}' | sort > centos # or debian or whatever.
```
The set of linked libs is the same for all the four binaries.
```
/usr/lib64/ld-2.23.so
/usr/lib64/libattr.so.1.1.0
/usr/lib64/libc-2.23.so
/usr/lib64/libcap.so.2.24
/usr/lib64/libdl-2.23.so
/usr/lib64/libgcrypt.so.20.1.3
/usr/lib64/libgpg-error.so.0.19.1
/usr/lib64/liblzma.so.5.2.2
/usr/lib64/libnss_dns-2.23.so
/usr/lib64/libnss_files-2.23.so
/usr/lib64/libnss_usrfiles.so.2
/usr/lib64/libpcre.so.1.2.7
/usr/lib64/libpthread-2.23.so
/usr/lib64/libresolv-2.23.so
/usr/lib64/librt-2.23.so
/usr/lib64/libselinux.so.1
/usr/lib64/libsystemd.so.0.18.0
```

Moreover if you look at https://github.com/systemd/systemd/tree/master/src/journal you'll notice that most of the header files have not changed for two years. ( _this is what I call stability ;)_ )
And header files is the only thing from the systemd sources we need to build the resulting binary actually.

I see no reason for shipping three different binaries which are pretty much the same under the hood and reading systemd journal fully depends on the presence of `libsystemd.so` and compliance of the headers used for building `journalbeat` to the libraries linked against.

Journald API backwards compatibility at work!
