### ISSUE TITLE
Support for syslog identifiers (journalctl -t) 

### ISSUE THREAD

**Issue by jalaziz** [mheese/journalbeat#94]
It would be great if journalbeat could support filtering on syslog identifiers as well as unit names. This would allow capturing logs for processes that log exclusively via syslog.

**Comment by hookenz** [comment]
That should be easy.  So for example, 

    journalctl -t CRON

Shows cron scheduler events.  It would just be a matter of adding a filter for those.

**Comment by jalaziz** [comment]
Yeah. I've been meaning to send a PR. Just waiting for the systemd unit PR to land.

**Comment by hookenz** [comment]
@jalaziz - I'm waiting for that PR to be merged as well.

**Comment by hookenz** [comment]
@jalaziz - the systemd unit PR has landed.  Do you have PR for the above?  it would be useful.

**Comment by jalaziz** [comment]
@hookenz I'll have it ready tonight or tomorrow night!
